In [1]:

import json 
from urllib.request import Request, urlopen
import pandas as pd

#configs
pd.set_option("display.max_columns", None)

# Notes and foundings:

1) Hierarchy:
- Tournament
    - Rounds
        - Groups
            - Players
            - Games

2) There are players usernames in tournament, rounds and groups; use only groups, is the most complete.
3) No need to go parse pgn; all the important info is in groups.games.
4) the opennings are at groups.games too. (try to get probability wining of openning?)
5) We only use pre-game features, thus, signals like the opening ECO code, PGN, or result strings are excluded because they would leak the outcome.


# From documentation:

Game results codes:

- 'checkmated':'loss',
- 'win':'win',
- 'timeout':'loss',
- 'resigned':'loss',
- 'agreed': 'draw',
- '50move': 'draw',
- 'insufficient': 'draw',
- 'repetition' : 'draw',
- 'stalemate': 'draw',
- 'timevsinsufficient': 'draw',

In [2]:
tournaments =["https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327",
    "https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141"]

using documentation from : https://www.chess.com/news/view/published-data-api

In [3]:
# Documentation --> User-Agent: my-profile-tool/1.2 (username: your_username; contact: me@example.com)
USER_AGENT = "roberto-tool/1.0 (username: titorium; contact: roberto_arce_@hotmail.com)"

In [4]:
url = tournaments[1]
request = Request(url, headers={"User-Agent": USER_AGENT})
response = urlopen(request, timeout=30)
with urlopen(request, timeout=30) as response:
    tournament = json.load(response)

In [5]:
tournament

{'name': 'Titled-Tuesday-Blitz-March-10-2026',
 'url': 'https://www.chess.com/tournament/live/titled-tuesday-blitz-march-10-2026-6277141',
 'creator': 'CHESScom',
 'status': 'finished',
 'start_time': 1773158400,
 'finish_time': 1773166436,
 'settings': {'type': 'swiss',
  'rules': 'chess',
  'is_rated': True,
  'is_official': True,
  'is_invite_only': False,
  'user_advance_count': 1,
  'winner_places': 3,
  'registered_user_count': 476,
  'total_rounds': 11,
  'time_class': 'blitz',
  'time_control': '300'},
 'players': [{'username': 'sina-movahed', 'status': 'winner'},
  {'username': 'magnuscarlsen', 'status': 'registered'},
  {'username': 'denlaz', 'status': 'registered'},
  {'username': 'nikotheodorou', 'status': 'registered'},
  {'username': 'wonderfultime', 'status': 'registered'},
  {'username': 'mishanick', 'status': 'registered'},
  {'username': 'miterryble', 'status': 'registered'},
  {'username': 'konavets', 'status': 'registered'},
  {'username': 'piliposyanrobertchess', 'status': 'registered'},
  {'username': 'macho_2006', 'status': 'registered'},
  {'username': 'hakanazeri2', 'status': 'registered'},
  {'username': 'yosephtaher', 'status': 'registered'},
  {'username': 'nihalsarin', 'status': 'registered'},
  {'username': 'micki-taryan', 'status': 'registered'},
  {'username': 'fabianocaruana', 'status': 'registered'},
  {'username': 'gmbenjaminbok', 'status': 'registered'},
  {'username': 'fghsmn', 'status': 'registered'},
  {'username': 'kirill_klukin', 'status': 'registered'},
  {'username': 'polish_fighter3000', 'status': 'registered'},
  {'username': 'sanan_sjugirov', 'status': 'registered'},
  {'username': 'chesswarrior7197', 'status': 'registered'},
  {'username': 'shubinkirill2003', 'status': 'registered'},
  {'username': 'ghandeevam2003', 'status': 'registered'},
  {'username': 'cayse', 'status': 'registered'},
  {'username': 'nitzan_steinberg', 'status': 'registered'}],
 'rounds': ['https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/1',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/2',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/3',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/4',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/5',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/6',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/7',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/8',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/9',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/10',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-march-10-2026-6277141/11']}

In [6]:
url = tournaments[0]
request = Request(url, headers={"User-Agent": USER_AGENT})
response = urlopen(request, timeout=30)
with urlopen(request, timeout=30) as response:
    tournament = json.load(response)

In [7]:
tournament.keys()

dict_keys(['name', 'url', 'creator', 'status', 'start_time', 'finish_time', 'settings', 'players', 'rounds'])

In [8]:
tournament

{'name': 'Titled-Tuesday-Blitz-February-10-2026',
 'url': 'https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327',
 'creator': 'CHESScom',
 'status': 'finished',
 'start_time': 1770739200,
 'finish_time': 1770747355,
 'settings': {'type': 'swiss',
  'rules': 'chess',
  'is_rated': True,
  'is_official': True,
  'is_invite_only': False,
  'user_advance_count': 1,
  'winner_places': 3,
  'registered_user_count': 455,
  'total_rounds': 11,
  'time_class': 'blitz',
  'time_control': '300'},
 'players': [{'username': 'javokhir_sindarov05', 'status': 'winner'},
  {'username': 'konavets', 'status': 'registered'},
  {'username': 'nikotheodorou', 'status': 'registered'},
  {'username': 'jefferyx', 'status': 'registered'},
  {'username': 'bogdandeac', 'status': 'registered'},
  {'username': 'faustinooro', 'status': 'registered'},
  {'username': 'lyonbeast', 'status': 'registered'},
  {'username': 'grischuk', 'status': 'registered'},
  {'username': 'lachesisq', 'status': 'registered'},
  {'username': 'vincentkeymer', 'status': 'registered'},
  {'username': 'sanan_sjugirov', 'status': 'registered'},
  {'username': 'fairchess_on_youtube', 'status': 'registered'},
  {'username': 'polish_fighter3000', 'status': 'registered'},
  {'username': 'shimastream', 'status': 'registered'},
  {'username': 'zhuu96', 'status': 'registered'},
  {'username': 'miterryble', 'status': 'registered'},
  {'username': 'sibelephant', 'status': 'registered'},
  {'username': 'andreikka', 'status': 'registered'},
  {'username': 'amintabatabaei', 'status': 'registered'},
  {'username': 'anton_demchenko', 'status': 'registered'},
  {'username': 'rasmussvane', 'status': 'registered'},
  {'username': 'akewjon', 'status': 'registered'},
  {'username': 'superchess02', 'status': 'registered'},
  {'username': 'hikaru', 'status': 'registered'},
  {'username': 'dr_tyger', 'status': 'registered'}],
 'rounds': ['https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/1',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/2',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/3',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/4',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/5',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/6',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/7',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/8',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/9',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/10',
  'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/11']}

In [9]:
tournament['rounds']

['https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/1',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/2',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/3',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/4',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/5',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/6',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/7',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/8',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/9',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/10',
 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/11']

In [10]:
tournament['players'].__len__()

25

only 25 players?

In [11]:
tournament.keys()

dict_keys(['name', 'url', 'creator', 'status', 'start_time', 'finish_time', 'settings', 'players', 'rounds'])

In [12]:
for round in tournament["rounds"]:
    print(round)

https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/1
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/2
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/3
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/4
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/5
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/6
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/7
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/8
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/9
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/10
https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/11

In [13]:
roundd = tournament["rounds"][0]
round_response = urlopen(roundd, timeout=30)
round_data = json.load(round_response)
round_data.keys()

dict_keys(['groups', 'players'])

In [14]:
round_data

{'groups': ['https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/1/1'],
 'players': [{'username': 'umuterdemgunduz'},
  {'username': 'lachesisq'},
  {'username': 'jaisankars'},
  {'username': 'gmwso'},
  {'username': 'dey2580'},
  {'username': 'oleksandr_bortnyk'},
  {'username': 'pizzalover2502'},
  {'username': 'fairchess_on_youtube'},
  {'username': 'yohankrokov'},
  {'username': 'polish_fighter3000'},
  {'username': 'cosmokramer2260'},
  {'username': 'parhamov'},
  {'username': 'itay121'},
  {'username': 'miterryble'},
  {'username': 'gh6999'},
  {'username': 'faustinooro'},
  {'username': 'egehany09'},
  {'username': 'sina-movahed'},
  {'username': 'il_cavallo_matto'},
  {'username': 'chesswarrior7197'},
  {'username': 'lion-al-messi'},
  {'username': 'artooon'},
  {'username': 'kaidanov'},
  {'username': 'andreikka'},
  {'username': 'nastyahn'},
  {'username': 'grischuk'},
  {'username': 'kasimovr21'},
  {'username': 'fabianocaruana'},
  {'username': 'fh2411'},
  {'username': 'sergoy'},
  {'username': 'nobodyjeroen'},
  {'username': 'rezamahdavi2008'},
  {'username': 'patricius007'},
  {'username': 'rud_makarian'},
  {'username': 'coachsuhaas'},
  {'username': 'suyarov1'},
  {'username': 'janmur7'},
  {'username': 'frederiksvane'},
  {'username': 'smiechu'},
  {'username': 'sanan_sjugirov'},
  {'username': 'apollonzerotv'},
  {'username': 'turboplombir'},
  {'username': 'ybothg'},
  {'username': 'vaathi_coming'},
  {'username': 'guillead1'},
  {'username': 'chito89'},
  {'username': 'alomaterapia'},
  {'username': 'ohanyaneminchess'},
  {'username': 'elnaz_kaliakhmet'},
  {'username': 'angry_twin'},
  {'username': 'dosto07'},
  {'username': 'gmbenjaminbok'},
  {'username': 'kielinkei'},
  {'username': 'beca95'},
  {'username': 'wunderkind2011'},
  {'username': 'gmakobianstl'},
  {'username': 'infiniteflo'},
  {'username': 'crescentmoon2411'},
  {'username': 'hephaestus_11'},
  {'username': 'kirill_klukin'},
  {'username': 'jup1978'},
  {'username': 'cayse'},
  {'username': 'alejandro2006lara'},
  {'username': 'formerprodigy'},
  {'username': 'lukaslebakken'},
  {'username': 'goshachai2010'},
  {'username': 'mr-uteligger'},
  {'username': 'jcibarra'},
  {'username': 'cristianchess19'},
  {'username': 'iball95'},
  {'username': 'miki_gb'},
  {'username': 'tsaruk_maks'},
  {'username': 'komogro'},
  {'username': 'dretch'},
  {'username': 'queladri'},
  {'username': 'pouya21'},
  {'username': 'alex_banzea'},
  {'username': 'sam_chessmood'},
  {'username': 'sultaic'},
  {'username': 'nitzan_steinberg'},
  {'username': 'deenzerz'},
  {'username': 'klimkoj'},
  {'username': 'sleeping_in_the_fire'},
  {'username': 'mitrabhaa'},
  {'username': 'manukyan_artak'},
  {'username': 'qminhlcf'},
  {'username': 'bencus12'},
  {'username': 'alexrustemov'},
  {'username': 'mapl3man'},
  {'username': 'byniolus'},
  {'username': 'cartonmaster'},
  {'username': 'chesniu'},
  {'username': 'eloist'},
  {'username': 'superchess02'},
  {'username': 'witty_alien'},
  {'username': 'csb7'},
  {'username': 'nastypanda'},
  {'username': 'germanovs_georgijs'},
  {'username': 'windwhistler11'},
  {'username': 'darkalekhine'},
  {'username': 'futurechamp1907'},
  {'username': 'wmirbv'},
  {'username': 'ananya2898'},
  {'username': 'darkknight_0102'},
  {'username': 'nitalucian'},
  {'username': 'minisim'},
  {'username': 'gaidym72'},
  {'username': 'nodariousbig'},
  {'username': 'gasparasprelliok'},
  {'username': 'gangster-accountant01'},
  {'username': 'maurijs'},
  {'username': 'kingnb'},
  {'username': 'pesandu_liyanage_1'},
  {'username': 'wise_guyyy'},
  {'username': 'dimoointheworld'},
  {'username': 'krzyzan94'},
  {'username': 'cocosiukas'},
  {'username': 'vovachesss'},
  {'username': 'r-sham'},
  {'username': 'allcer7'},
  {'username': 'ket_cha'},
  {'username': 'iljiushenok_ilya'},
  {'username': 'baratheont'},
  {'username': 'szparu'},
  {'username': 'oleksandrprokhorov'},
  {'username': 'zurability'},
  {'username': 'kulik2007'},
  {'username': 'slidingknight2775'},
  {'username': 'gen-gutman'},
  {'username': 'beltraxtor'},
  {'username': 'arlan_mirzhanov'},
  {'username': 'kildepiotr'},
  {'username': 'gabriel_pereyra'},
  {'username': 'whiteking2009'},
  {'username': 'seasidesunset'},
  {'username': 'ykow2'},
  {'username': 'enzoferrara'},
  {'username': 'reshetkov'},
  {'username': 'endgamedestroyer'},
  {'username': 'roseatwell'},
  {'username': 'hatsak7'},
  {'username': 'granatomet552'},
  {'username': 'matvii_b'},
  {'username': 'emperor87'},
  {'username': 'mjelcic'},
  {'username': 'gedizov'},
  {'username': 'barriochess'},
  {'username': 'khazhatuly_alikhan'},
  {'username': 'ivandrade10'},
  {'username': 'elcandado'},
  {'username': 'gabrielcarckeno'},
  {'username': 'nikavolkov'},
  {'username': 'liondinamic'},
  {'username': 'mw86'},
  {'username': 'ridethesky89'},
  {'username': 'bullycloud'},
  {'username': 'gobiquanvo'},
  {'username': 'ant_chess_2019'},
  {'username': 'danifv'},
  {'username': 'der_balak_3halak'},
  {'username': 'garnikn'},
  {'username': 'georgiossouleidis'},
  {'username': 'ach19'},
  {'username': 'dontmesswiththefish'},
  {'username': 'tonilator'},
  {'username': 'karinachess1'},
  {'username': 'janjestem'},
  {'username': 'allblacksgoat'},
  {'username': 'ferdipy'},
  {'username': 'chesskhan11'},
  {'username': 'xuetianhao'},
  {'username': 'maurinm'},
  {'username': 'fmalexhdez'},
  {'username': 'zoktayyyyfanclubbb'},
  {'username': 'masteratracos'},
  {'username': 'im_alex_ivanov'},
  {'username': 'mise2020'},
  {'username': 'endgamemaster51'},
  {'username': 'ludin-esteban-jaimes-gonz'},
  {'username': 'gennady_kozlov'},
  {'username': 'jan2404'},
  {'username': 'm_ezat'},
  {'username': 'tiagomangialardo'},
  {'username': 'tetrix83'},
  {'username': 'cheessmasteer54'},
  {'username': 'beawuids'},
  {'username': 'alenzer'},
  {'username': 'andrew-blr'},
  {'username': 'thesmallergreek'},
  {'username': 'dawidczerw'},
  {'username': 'eugenefurman'},
  {'username': 'logicbaba'},
  {'username': 'mcwzpk'},
  {'username': 'trojan-knight'},
  {'username': 'viper_108'},
  {'username': 'robert_sava'},
  {'username': 'katheringomezarias'},
  {'username': 'chessbaerchen'},
  {'username': 'ahmed_naser1'},
  {'username': 'therabbit19'},
  {'username': 'pfalcon1949'},
  {'username': 'liusia'},
  {'username': 'hikaru'},
  {'username': 'gorindeshi'},
  {'username': 'nikotheodorou'},
  {'username': 'gcamachomartinez'},
  {'username': 'ghandeevam2003'},
  {'username': 'sn2022s'},
  {'username': 'sibelephant'},
  {'username': 'theinfinity011'},
  {'username': 'micki-taryan'},
  {'username': 'vladgoncharov'},
  {'username': 'konavets'},
  {'username': 'maxleto'},
  {'username': 'bogdandeac'},
  {'username': 'mattheii'},
  {'username': 'mishanick'},
  {'username': 'mwpchess'},
  {'username': 'wonderfultime'},
  {'username': 'mathiascasalaspro'},
  {'username': 'lyonbeast'},
  {'username': 'nigirisushies'},
  {'username': 'jefferyx'},
  {'username': 'bazar-wokzal'},
  {'username': 'javokhir_sindarov05'},
  {'username': 'vesper2018'},
  {'username': 'msb2'},
  {'username': 'juan-jose-taylor-rodrigue'},
  {'username': 'chessfighter_2011'},
  {'username': 'earlybird2012'},
  {'username': 'amintabatabaei'},
  {'username': 'kingside_rook'},
  {'username': 'gm_dmitrij'},
  {'username': 'samdanov'},
  {'username': 'zhuu96'},
  {'username': 'kz_champ_gm'},
  {'username': 'vincentkeymer'},
  {'username': 'drwonderkid'},
  {'username': 'shield12'},
  {'username': 'opqrc'},
  {'username': 'shimastream'},
  {'username': 'midgardsormur'},
  {'username': 'igor_janik'},
  {'username': 'nexoknight11'},
  {'username': 'matthewg-p4p'},
  {'username': 'kimkibo'},
  {'username': 'sergeant_james'},
  {'username': 'ural58'},
  {'username': 'rasmussvane'},
  {'username': 'saihanthiha'},
  {'username': 'harsha_bharathakoti'},
  {'username': 'wpwpwp-2015'},
  {'username': 'anton_demchenko'},
  {'username': 'joliyroger'},
  {'username': 'jumbo'},
  {'username': 'noname372k'},
  {'username': 'piliposyanrobertchess'},
  {'username': 'actuary44'},
  {'username': 'ilqar_74'},
  {'username': 'vm2027'},
  {'username': 'dr_tyger'},
  {'username': 'mammadzadag'},
  {'username': 'whiteknight2612'},
  {'username': 'bapttoche'},
  {'username': 'metiforce'},
  {'username': 'chuessco'},
  {'username': 'durarbayli'},
  {'username': 'gmfyhr1'},
  {'username': 'knvb'},
  {'username': 'tiltedknight123'},
  {'username': 'trahtarbelarus'},
  {'username': 'mcqueen444'},
  {'username': 'ckgchess'},
  {'username': 'stt170116'},
  {'username': 'kosak12'},
  {'username': 'asvz'},
  {'username': 'jakopogi'},
  {'username': 'kotofeyca'},
  {'username': 'stollenmonster'},
  {'username': 'ljuks68'},
  {'username': 'robertojbm'},
  {'username': 'teresin05'},
  {'username': 'fghsmn'},
  {'username': 'safikiet'},
  {'username': 'moro182'},
  {'username': 'propellerboy01'},
  {'username': 'alexander_donchenko'},
  {'username': 'madeinleningrad'},
  {'username': 'lamomiajunior'},
  {'username': 'deanklobucar'},
  {'username': 'iwanyu'},
  {'username': 'niviattack'},
  {'username': 'garayevkanan'},
  {'username': 'cherneevo_23'},
  {'username': 'aa175'},
  {'username': 'sofiia_hryzlova'},
  {'username': 'a-fier'},
  {'username': 'mostafasakha'},
  {'username': 'flawless_fighter'},
  {'username': 'rcc_2024'},
  {'username': 'alexpapasimakopoulos'},
  {'username': 'bonantagulo'},
  {'username': 'tunartank'},
  {'username': 'mikhal867'},
  {'username': 'gm_path'},
  {'username': 'shahzodbek_2010'},
  {'username': 'shavkatov02'},
  {'username': 'cheer_down'},
  {'username': 'only_strong_moves'},
  {'username': 'fischerbobbyjames'},
  {'username': 'alexboy14'},
  {'username': 'recombinant'},
  {'username': 'slipperyspeedster'},
  {'username': 'miguel-la'},
  {'username': 'individoom'},
  {'username': 'battery_chess'},
  {'username': 'frederickthemate'},
  {'username': 'hyuslin'},
  {'username': 'alen_chessmate'},
  {'username': 'gambitgiesbergen'},
  {'username': 'boundless_strike'},
  {'username': 'francesatop'},
  {'username': 'colleofduty'},
  {'username': 'saranyadevinarahari'},
  {'username': 'nikitashandrygin'},
  {'username': 'tugaychess'},
  {'username': 'ganiev_artur11'},
  {'username': 'godzillator'},
  {'username': 'caroexpert'},
  {'username': 'venemycin'},
  {'username': 'pavle896'},
  {'username': 'acidshazz'},
  {'username': 'm_pank_537'},
  {'username': 'premierchess64'},
  {'username': 'rafaelsharon'},
  {'username': 'shivananda1964'},
  {'username': 'chomiczek786'},
  {'username': 'knightinshiningarmour16'},
  {'username': 'gianmarco_es'},
  {'username': 'xyloxia'},
  {'username': 'sajid0987654321'},
  {'username': 'cabezauro'},
  {'username': 'meri-arabidze'},
  {'username': 'yushko_olga'},
  {'username': 'nikolakis2014'},
  {'username': 'hilleltoledo'},
  {'username': 'viktorskliarov'},
  {'username': 'willi_skibbe'},
  {'username': 'ginger_gm'},
  {'username': 'tuongminhcute'},
  {'username': 'antoni_radzimski'},
  {'username': 'luisfsiles'},
  {'username': 'akewjon'},
  {'username': 'weezhun93'},
  {'username': 'manitodeplomo'},
  {'username': 'x-6605293955'},
  {'username': 'anasta10'},
  {'username': 'timur_nurzhanov'},
  {'username': 'nicki2013'},
  {'username': 'navyblue1'},
  {'username': 'speshka'},
  {'username': 'taglit'},
  {'username': 'oliver_wartiovaara'},
  {'username': 'albadelomass'},
  {'username': 'xiaoxuan2012'},
  {'username': 'hannahsaycestreams'},
  {'username': 'bulletteemo'},
  {'username': 'mirchi_26'},
  {'username': 'keithonsky'},
  {'username': 'ramu_k_fm_ft'},
  {'username': 'lerry0525'},
  {'username': 'elessar16'},
  {'username': 'fariza2018'},
  {'username': 'lordiron'},
  {'username': 'casper'},
  {'username': 'lopesakalopes'},
  {'username': 'rollercoaster29'},
  {'username': 'chessgirl_leyla'},
  {'username': 'sammed_shete'},
  {'username': 'zeronybah'},
  {'username': 'yyaroslavchess2010'},
  {'username': 'hrvojezagreb'},
  {'username': 'aryan_tamadon'},
  {'username': 'lacafi'},
  {'username': 'gryffindorac8'},
  {'username': 'irina_mikhaylova'},
  {'username': 'crazy_m_attack'},
  {'username': 'jaroslavsobek'},
  {'username': 'mikakarttunen'},
  {'username': 'matinghaffarifar'},
  {'username': 'wgraif'},
  {'username': 'mikewizard'},
  {'username': 'stormstrategist'},
  {'username': 'saara_sunea'},
  {'username': 'aloe_normansen'},
  {'username': 'shirovin'},
  {'username': 'grotbchess'},
  {'username': 'sevilplayschess'},
  {'username': 'semetey'},
  {'username': 'marcbarcelo'},
  {'username': 'nbk90'},
  {'username': 'magnusshawa_chess'},
  {'username': 'eleyah'},
  {'username': 'kashthuri3'}]}

In [15]:
round_data['players'].__len__()

404

there are more players in round than in tournament?

In [16]:
round_data['groups'][0]

'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327/1/1'

In [17]:
group_response = urlopen(round_data['groups'][0], timeout=30)
group_data = json.load(group_response)

In [18]:
group_data

{'games': [{'url': 'https://www.chess.com/game/live/165052787661',
   'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "UmutErdemGunduz"]\n[Black "Hikaru"]\n[Result "0-1"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54"]\n[Timezone "UTC"]\n[ECO "B06"]\n[ECOUrl "https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "2682"]\n[BlackElo "3316"]\n[TimeControl "300"]\n[Termination "Hikaru won on time"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:09:53"]\n[Link "https://www.chess.com/game/live/165052787661"]\n\n1. e4 {[%clk 0:04:59.3]} 1... g6 {[%clk 0:04:34.6]} 2. d4 {[%clk 0:04:57.6]} 2... Bg7 {[%clk 0:04:32.7]} 3. Nf3 {[%clk 0:04:56.6]} 3... a6 {[%clk 0:04:30.3]} 4. c4 {[%clk 0:04:51.4]} 4... d6 {[%clk 0:03:59.5]} 5. Nc3 {[%clk 0:04:50]} 5... Bg4 {[%clk 0:03:58.1]} 6. Be3 {[%clk 0:04:41.8]} 6... Nd7 {[%clk 0:03:53.8]} 7. h3 {[%clk 0:04:36.2]} 7... Bxf3 {[%clk 0:03:52.2]} 8. Qxf3 {[%clk 0:04:36.1]} 8... c5 {[%clk 0:03:45.8]} 9. d5 {[%clk 0:04:11.2]} 9... Ngf6 {[%clk 0:03:36.7]} 10. Qd1 {[%clk 0:04:03.5]} 10... O-O {[%clk 0:03:35.4]} 11. Be2 {[%clk 0:04:01]} 11... b5 {[%clk 0:03:30]} 12. Qc2 {[%clk 0:03:28.4]} 12... bxc4 {[%clk 0:03:14.9]} 13. Bxc4 {[%clk 0:03:28.3]} 13... Qa5 {[%clk 0:02:51.5]} 14. O-O {[%clk 0:03:21.9]} 14... Rfb8 {[%clk 0:02:49.4]} 15. a3 {[%clk 0:03:05.3]} 15... Rb7 {[%clk 0:02:37.2]} 16. Rfb1 {[%clk 0:02:37.7]} 16... Rab8 {[%clk 0:02:27.6]} 17. b4 {[%clk 0:02:23.8]} 17... cxb4 {[%clk 0:02:23.5]} 18. axb4 {[%clk 0:02:23.2]} 18... Qc7 {[%clk 0:02:22.7]} 19. Bxa6 {[%clk 0:02:07.1]} 19... Rxb4 {[%clk 0:02:21.7]} 20. Rxb4 {[%clk 0:01:55]} 20... Rxb4 {[%clk 0:02:21.6]} 21. Bd3 {[%clk 0:01:50.6]} 21... Rb8 {[%clk 0:01:54.4]} 22. Ra7 {[%clk 0:01:47.9]} 22... Qc8 {[%clk 0:01:53.6]} 23. Ba6 {[%clk 0:01:43.4]} 23... Qd8 {[%clk 0:01:51.1]} 24. Nb5 {[%clk 0:01:40.5]} 24... Nc5 {[%clk 0:01:44.3]} 25. Bxc5 {[%clk 0:01:17.2]} 25... dxc5 {[%clk 0:01:44.2]} 26. Qxc5 {[%clk 0:01:16.9]} 26... Nxe4 {[%clk 0:01:42.8]} 27. Qxe7 {[%clk 0:01:12.5]} 27... Qxd5 {[%clk 0:01:19.1]} 28. Bb7 {[%clk 0:00:58.8]} 28... Qd1+ {[%clk 0:00:55]} 29. Kh2 {[%clk 0:00:58.3]} 29... Nd2 {[%clk 0:00:54.5]} 30. Ra8 {[%clk 0:00:31.7]} 30... Nf1+ {[%clk 0:00:51.7]} 31. Kg1 {[%clk 0:00:29.1]} 31... Nd2+ {[%clk 0:00:51.6]} 32. Kh2 {[%clk 0:00:28.3]} 32... Rxa8 {[%clk 0:00:51.3]} 33. Bxa8 {[%clk 0:00:27.2]} 33... Nf1+ {[%clk 0:00:50.9]} 34. Kg1 {[%clk 0:00:25.9]} 34... Nd2+ {[%clk 0:00:50.8]} 35. Kh2 {[%clk 0:00:25.3]} 35... Bf8 {[%clk 0:00:50.7]} 36. Qe8 {[%clk 0:00:19.5]} 36... Nf1+ {[%clk 0:00:49.9]} 37. Kg1 {[%clk 0:00:18.9]} 37... Ne3+ {[%clk 0:00:41.5]} 38. Kh2 {[%clk 0:00:17.8]} 38... Nf5 {[%clk 0:00:41.4]} 39. Bf3 {[%clk 0:00:14.4]} 39... Qd2 {[%clk 0:00:38.3]} 40. Qe2 {[%clk 0:00:12.5]} 40... Qb4 {[%clk 0:00:35.9]} 41. g3 {[%clk 0:00:11.8]} 41... h5 {[%clk 0:00:34.4]} 42. Kg2 {[%clk 0:00:11.3]} 42... h4 {[%clk 0:00:33.3]} 43. g4 {[%clk 0:00:10.9]} 43... Ng7 {[%clk 0:00:33]} 44. Bd5 {[%clk 0:00:09.9]} 44... Qc5 {[%clk 0:00:32.1]} 45. Qc4 {[%clk 0:00:09]} 45... Qe7 {[%clk 0:00:31.2]} 46. Nd4 {[%clk 0:00:06.8]} 46... Ne8 {[%clk 0:00:30]} 47. Nf3 {[%clk 0:00:06.2]} 47... Nf6 {[%clk 0:00:28.4]} 48. Ng5 {[%clk 0:00:04.5]} 48... Qe5 {[%clk 0:00:26.7]} 49. Bxf7+ {[%clk 0:00:03.6]} 49... Kg7 {[%clk 0:00:26.4]} 50. Ne6+ {[%clk 0:00:02.4]} 50... Kxf7 {[%clk 0:00:24.7]} 51. Ng5+ {[%clk 0:00:01.3]} 51... Ke7 {[%clk 0:00:24]} 52. Qf7+ {[%clk 0:00:00.9]} 52... Kd6 {[%clk 0:00:23.6]} 53. Qxf8+ {[%clk 0:00:00.3]} 53... Kc6 {[%clk 0:00:23.3]} 0-1\n',
   'time_control': '300',
   'end_time': 1770739793,
   'rated': True,
   'fen': '5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54',
   'time_class': 'blitz',
   'rules': 'chess',
   'white': {'rating': 2682,
    'result': 'timeout',
    '@id': 'https://api.chess.com/pub/player/umuterdemgunduz',
    'username': 'UmutErdemGunduz',
    'uuid': '0016479a-a347-11e9-b619-7d5b9e8b8800'},
   'black': {'rating': 3316,
    'result': 'win',
    '@id': 'https://api.chess.com/pub/player/hikaru',
    'username': 'Hikaru',
    'uuid': '6f4deb88-7718-11e3-8016-000000000000'},
   'eco': 'https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3',
   'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'},
  {'url': 'https://www.chess.com/game/live/165052787663',
   'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "lachesisQ"]\n[Black "GorinDeshi"]\n[Result "1-0"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "3r1k2/p1R1p2b/4N3/4R3/P5p1/1P4P1/2P4r/2K5 b - - 2 35"]\n[Timezone "UTC"]\n[ECO "B76"]\n[ECOUrl "https://www.chess.com/openings/Sicilian-Defense-Open-Dragon-Rauzer-Variation-9...d5-10.Nxc6-bxc6-11.Bh6"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "3279"]\n[BlackElo "2678"]\n[TimeControl "300"]\n[Termination "lachesisQ won by resignation"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:06:37"]\n[Link "https://www.chess.com/game/live/165052787663"]\n\n1. e4 {[%clk 0:04:59.9]} 1... c5 {[%clk 0:04:58.4]} 2. Nf3 {[%clk 0:04:58.5]} 2... d6 {[%clk 0:04:56]} 3. d4 {[%clk 0:04:57.9]} 3... cxd4 {[%clk 0:04:55.9]} 4. Nxd4 {[%clk 0:04:57.8]} 4... Nf6 {[%clk 0:04:55]} 5. Nc3 {[%clk 0:04:57.6]} 5... g6 {[%clk 0:04:53.8]} 6. Be3 {[%clk 0:04:54.5]} 6... Bg7 {[%clk 0:04:53.1]} 7. f3 {[%clk 0:04:54]} 7... O-O {[%clk 0:04:52.2]} 8. Qd2 {[%clk 0:04:53.7]} 8... Nc6 {[%clk 0:04:51.5]} 9. O-O-O {[%clk 0:04:53.4]} 9... d5 {[%clk 0:04:50.8]} 10. Nxc6 {[%clk 0:04:52.8]} 10... bxc6 {[%clk 0:04:47.5]} 11. Bh6 {[%clk 0:04:52.5]} 11... Be6 {[%clk 0:04:14.4]} 12. h4 {[%clk 0:04:48.5]} 12... dxe4 {[%clk 0:04:11.2]} 13. Bxg7 {[%clk 0:04:20.9]} 13... Qxd2+ {[%clk 0:04:02.4]} 14. Rxd2 {[%clk 0:04:20.8]} 14... Kxg7 {[%clk 0:04:01.7]} 15. fxe4 {[%clk 0:04:15.2]} 15... Rfd8 {[%clk 0:03:55.4]} 16. Be2 {[%clk 0:04:14.4]} 16... h5 {[%clk 0:03:30.7]} 17. b3 {[%clk 0:04:10.4]} 17... Ng4 {[%clk 0:03:24.9]} 18. Bxg4 {[%clk 0:04:08.1]} 18... hxg4 {[%clk 0:03:23.5]} 19. g3 {[%clk 0:04:07.3]} 19... Kf6 {[%clk 0:03:07.3]} 20. Rhd1 {[%clk 0:04:05.6]} 20... Rh8 {[%clk 0:02:59.3]} 21. Ne2 {[%clk 0:04:03.3]} 21... g5 {[%clk 0:02:55.7]} 22. hxg5+ {[%clk 0:03:50]} 22... Kxg5 {[%clk 0:02:54.7]} 23. Nd4 {[%clk 0:03:49.5]} 23... Rh3 {[%clk 0:02:44]} 24. Rd3 {[%clk 0:03:47.4]} 24... Bd7 {[%clk 0:02:36.5]} 25. Ne2 {[%clk 0:03:42.9]} 25... Be6 {[%clk 0:02:21.4]} 26. Rc3 {[%clk 0:03:41.7]} 26... Rh2 {[%clk 0:01:54.5]} 27. Nf4 {[%clk 0:03:40.3]} 27... Bc8 {[%clk 0:01:33.6]} 28. Rc5+ {[%clk 0:03:36.2]} 28... f5 {[%clk 0:01:25.1]} 29. exf5 {[%clk 0:03:33]} 29... Bxf5 {[%clk 0:01:21.1]} 30. Re1 {[%clk 0:03:32.5]} 30... Kf6 {[%clk 0:01:09.9]} 31. Rxc6+ {[%clk 0:03:28.7]} 31... Kf7 {[%clk 0:01:03.2]} 32. Rc7 {[%clk 0:03:27.6]} 32... Kf8 {[%clk 0:00:58.6]} 33. Re5 {[%clk 0:03:22.8]} 33... Bh7 {[%clk 0:00:47.1]} 34. a4 {[%clk 0:03:06.6]} 34... Rd8 {[%clk 0:00:37.8]} 35. Ne6+ {[%clk 0:03:05.5]} 1-0\n',
   'time_control': '300',
   'end_time': 1770739597,
   'rated': True,
   'fen': '3r1k2/p1R1p2b/4N3/4R3/P5p1/1P4P1/2P4r/2K5 b - - 2 35',
   'time_class': 'blitz',
   'rules': 'chess',
   'white': {'rating': 3279,
    'result': 'win',
    '@id': 'https://api.chess.com/pub/player/lachesisq',
    'username': 'lachesisQ',
    'uuid': 'ea103016-2647-11e6-8040-000000000000'},
   'black': {'rating': 2678,
    'result': 'resigned',
    '@id': 'https://api.chess.com/pub/player/gorindeshi',
    'username': 'GorinDeshi',
    'uuid': 'af27c69c-36ef-11ee-afee-879979d51b45'},
   'eco': 'https://www.chess.com/openings/Sicilian-Defense-Open-Dragon-Rauzer-Variation-9...d5-10.Nxc6-bxc6-11.Bh6',
   'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'},
  {'url': 'https://www.chess.com/game/live/165052787665',
   'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "JaiSankarS"]\n[Black "NikoTheodorou"]\n[Result "0-1"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "8/8/6k1/5p2/5PK1/6P1/8/7q w - f6 0 55"]\n[Timezone "UTC"]\n[ECO "A15"]\n[ECOUrl "https://www.chess.com/openings/English-Opening-Anglo-Indian-Kings-Knight-Queens-Indian-Formation...6.O-O-O-O-7.Nc3-Ne4"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "2677"]\n[BlackElo "3252"]\n[TimeControl "300"]\n[Termination "NikoTheodorou won by checkmate"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:06:42"]\n[Link "https://www.chess.com/game/live/165052787665"]\n\n1. Nf3 {[%clk 0:04:59.6]} 1... Nf6 {[%clk 0:04:58.9]} 2. g3 {[%clk 0:04:56.1]} 2... b6 {[%clk 0:04:57.8]} 3. Bg2 {[%clk 0:04:56]} 3... Bb7 {[%clk 0:04:57.7]} 4. O-O {[%clk 0:04:55.9]} 4... g6 {[%clk 0:04:57.3]} 5. c4 {[%clk 0:04:54.3]} 5... Bg7 {[%clk 0:04:56.5]} 6. Nc3 {[%clk 0:04:54.2]} 6... O-O {[%clk 0:04:55.9]} 7. d4 {[%clk 0:04:53.8]} 7... Ne4 {[%clk 0:04:55.4]} 8. Bf4 {[%clk 0:04:50]} 8... Nxc3 {[%clk 0:04:46.5]} 9. bxc3 {[%clk 0:04:49.9]} 9... Nc6 {[%clk 0:04:46.2]} 10. Ne5 {[%clk 0:04:45.6]} 10... Na5 {[%clk 0:04:40.2]} 11. Bxb7 {[%clk 0:04:39.5]} 11... Nxb7 {[%clk 0:04:40.1]} 12. Qd2 {[%clk 0:04:39.3]} 12... Na5 {[%clk 0:04:38.2]} 13. c5 {[%clk 0:04:34.2]} 13... d6 {[%clk 0:04:29.2]} 14. cxd6 {[%clk 0:04:33.3]} 14... cxd6 {[%clk 0:04:29.1]} 15. Nf3 {[%clk 0:04:30.2]} 15... Rc8 {[%clk 0:04:28.2]} 16. Rfc1 {[%clk 0:04:28.4]} 16... Nc4 {[%clk 0:04:19.5]} 17. Qd3 {[%clk 0:04:23.6]} 17... Qd7 {[%clk 0:04:18.9]} 18. a4 {[%clk 0:04:17.6]} 18... Rc7 {[%clk 0:04:15.1]} 19. Nd2 {[%clk 0:04:15.1]} 19... Rfc8 {[%clk 0:04:12.5]} 20. Nxc4 {[%clk 0:04:13.4]} 20... Rxc4 {[%clk 0:04:12.4]} 21. Bd2 {[%clk 0:04:12.7]} 21... Rxa4 {[%clk 0:04:10.3]} 22. c4 {[%clk 0:04:07.5]} 22... Rcxc4 {[%clk 0:03:57.2]} 23. Qxc4 {[%clk 0:04:04.2]} 23... Rxc4 {[%clk 0:03:55.9]} 24. Rxc4 {[%clk 0:04:04.1]} 24... h5 {[%clk 0:03:21.9]} 25. Rac1 {[%clk 0:04:00.6]} 25... Bf6 {[%clk 0:03:13.5]} 26. d5 {[%clk 0:03:49.7]} 26... Kg7 {[%clk 0:03:07.7]} 27. e4 {[%clk 0:03:47.7]} 27... h4 {[%clk 0:03:05]} 28. Be3 {[%clk 0:03:38.1]} 28... h3 {[%clk 0:02:58.9]} 29. f3 {[%clk 0:03:36.6]} 29... Qb5 {[%clk 0:02:54.4]} 30. Kf2 {[%clk 0:03:33.1]} 30... Qb2+ {[%clk 0:02:49]} 31. R4c2 {[%clk 0:03:31.1]} 31... Qb3 {[%clk 0:02:47.9]} 32. Rc7 {[%clk 0:03:24.1]} 32... a5 {[%clk 0:02:45.3]} 33. f4 {[%clk 0:03:16.5]} 33... Qd3 {[%clk 0:02:40.5]} 34. Kf3 {[%clk 0:03:04.6]} 34... Bd4 {[%clk 0:02:39.6]} 35. Re1 {[%clk 0:03:02.6]} 35... a4 {[%clk 0:02:17.2]} 36. Rxe7 {[%clk 0:02:54.9]} 36... a3 {[%clk 0:02:13.7]} 37. e5 {[%clk 0:02:50.1]} 37... Bxe3 {[%clk 0:02:09.6]} 38. Rxe3 {[%clk 0:02:48.1]} 38... Qxd5+ {[%clk 0:01:59.4]} 39. Kg4 {[%clk 0:02:47.6]} 39... a2 {[%clk 0:01:58.9]} 40. Ra7 {[%clk 0:02:39.6]} 40... Qd1+ {[%clk 0:01:56.8]} 41. Kxh3 {[%clk 0:02:37.6]} 41... a1=Q {[%clk 0:01:56]} 42. Rxa1 {[%clk 0:02:35.6]} 42... Qxa1 {[%clk 0:01:55.9]} 43. exd6 {[%clk 0:02:34]} 43... Qd4 {[%clk 0:01:55.1]} 44. Re5 {[%clk 0:02:28.1]} 44... Qxd6 {[%clk 0:01:54.1]} 45. Kg4 {[%clk 0:02:27.8]} 45... b5 {[%clk 0:01:52.9]} 46. h4 {[%clk 0:02:25.9]} 46... b4 {[%clk 0:01:52.1]} 47. h5 {[%clk 0:02:25.2]} 47... b3 {[%clk 0:01:50.9]} 48. hxg6 {[%clk 0:02:23.9]} 48... Qxg6+ {[%clk 0:01:47.3]} 49. Kf3 {[%clk 0:02:21.4]} 49... b2 {[%clk 0:01:46.2]} 50. Re1 {[%clk 0:02:17.7]} 50... b1=Q {[%clk 0:01:44.9]} 51. Rxb1 {[%clk 0:02:17.6]} 51... Qxb1 {[%clk 0:01:44.3]} 52. Kg4 {[%clk 0:02:17.4]} 52... Kg6 {[%clk 0:01:43.3]} 53. Kh4 {[%clk 0:02:15.6]} 53... Qh1+ {[%clk 0:01:42.1]} 54. Kg4 {[%clk 0:02:14.5]} 54... f5# {[%clk 0:01:41.8]} 0-1\n',
   'time_control': '300',
   'end_time': 1770739602,
   'rated': True,
   'fen': '8/8/6k1/5p2/5PK1/6P1/8/7q w - f6 0 55',
   'time_class': 'blitz',
   'rules': 'chess',
   'white': {'rating': 2677,
    'result': 'checkmated',
    '@id': 'https://api.chess.com/pub/player/jaisankars',
    'username': 'JaiSankarS',
    'uuid': 'cb754d68-e4f6-11ef-a68a-9be73e69b3c8'},
   'black': {'rating': 3252,
    'result': 'win',
    '@id': 'https://api.chess.com/pub/player/nikotheodorou',
    'username': 'NikoTheodorou',
    'uuid': '4d8a88c8-4b2b-11eb-89ec-1b7cb3f4e61a'},
   'eco': 'https://www.chess.com/openings/English-Opening-Anglo-Indian-Kings-Knight-Queens-Indian-Formation...6.O-O-O-O-7.Nc3-Ne4',
   'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'},
  {'url': 'https://www.chess.com/game/live/165052787667',
   'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "GMWSO"]\n[Black "GCamachoMartinez"]\n[Result "0-1"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "3r4/1p5R/2p1b2P/p1P5/5k2/PP2p2P/5p2/4KB2 w - - 0 43"]\n[Timezone "UTC"]\n[ECO "A01"]\n[ECOUrl "https://www.chess.com/openings/Nimzowitsch-Larsen-Attack-Modern-Variation-2.Bb2-d6"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "3230"]\n[BlackElo "2691"]\n[TimeControl "300"]\n[Termination "GCamachoMartinez won by resignation"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:08:09"]\n[Link "https://www.chess.com/game/live/165052787667"]\n\n1. b3 {[%clk 0:04:59.9]} 1... e5 {[%clk 0:04:58.1]} 2. Bb2 {[%clk 0:04:56.1]} 2... d6 {[%clk 0:04:57.3]} 3. d4 {[%clk 0:04:47.9]} 3... exd4 {[%clk 0:04:55.8]} 4. Nf3 {[%clk 0:04:46.9]} 4... Nf6 {[%clk 0:04:52.5]} 5. Nxd4 {[%clk 0:04:43.9]} 5... g6 {[%clk 0:04:50.7]} 6. c4 {[%clk 0:04:40.4]} 6... Bg7 {[%clk 0:04:49.7]} 7. g3 {[%clk 0:04:39.1]} 7... O-O {[%clk 0:04:48.6]} 8. Bg2 {[%clk 0:04:38.5]} 8... Re8 {[%clk 0:04:35.7]} 9. O-O {[%clk 0:04:36.3]} 9... Nbd7 {[%clk 0:04:34.7]} 10. Nc3 {[%clk 0:04:30.2]} 10... Nc5 {[%clk 0:04:29.5]} 11. Qc2 {[%clk 0:04:24.8]} 11... a5 {[%clk 0:04:19.6]} 12. Rad1 {[%clk 0:04:23.6]} 12... c6 {[%clk 0:04:15.6]} 13. a3 {[%clk 0:04:15.7]} 13... Qc7 {[%clk 0:04:07.2]} 14. Rd2 {[%clk 0:04:08.9]} 14... Bd7 {[%clk 0:03:54.3]} 15. Rfd1 {[%clk 0:04:05.6]} 15... Rad8 {[%clk 0:03:53.9]} 16. h3 {[%clk 0:03:58.8]} 16... Ne6 {[%clk 0:03:50.5]} 17. Nf3 {[%clk 0:03:56.2]} 17... Bc8 {[%clk 0:03:48]} 18. Kh2 {[%clk 0:03:53]} 18... Nc5 {[%clk 0:03:45.3]} 19. Nd4 {[%clk 0:03:46.7]} 19... Ne6 {[%clk 0:03:44]} 20. e3 {[%clk 0:03:42.7]} 20... Nxd4 {[%clk 0:03:41.9]} 21. Rxd4 {[%clk 0:03:42.3]} 21... Bf5 {[%clk 0:03:23.2]} 22. e4 {[%clk 0:03:31.1]} 22... Be6 {[%clk 0:03:03.3]} 23. f4 {[%clk 0:03:28.7]} 23... Nh5 {[%clk 0:02:49.5]} 24. R4d3 {[%clk 0:03:21.2]} 24... f5 {[%clk 0:02:48.6]} 25. Re3 {[%clk 0:03:12.2]} 25... g5 {[%clk 0:02:38.7]} 26. exf5 {[%clk 0:03:08.7]} 26... Bf7 {[%clk 0:02:25.7]} 27. Rxe8+ {[%clk 0:02:59.7]} 27... Rxe8 {[%clk 0:02:25.6]} 28. Ne4 {[%clk 0:02:58.2]} 28... gxf4 {[%clk 0:02:14.1]} 29. g4 {[%clk 0:02:50.5]} 29... f3 {[%clk 0:02:08.8]} 30. gxh5 {[%clk 0:02:36.1]} 30... d5+ {[%clk 0:02:02.5]} 31. Kg1 {[%clk 0:02:20.6]} 31... dxe4 {[%clk 0:02:01.3]} 32. Bxg7 {[%clk 0:02:20.1]} 32... Kxg7 {[%clk 0:02:00.3]} 33. h6+ {[%clk 0:02:06]} 33... Kf6 {[%clk 0:01:54.4]} 34. c5 {[%clk 0:01:47.3]} 34... Qg3 {[%clk 0:01:37.7]} 35. Rd6+ {[%clk 0:01:40.6]} 35... Kxf5 {[%clk 0:01:35.1]} 36. Rd7 {[%clk 0:01:40.1]} 36... Be6 {[%clk 0:01:21.7]} 37. Rg7 {[%clk 0:01:37.1]} 37... Qe1+ {[%clk 0:01:13.7]} 38. Bf1 {[%clk 0:01:34.5]} 38... Rd8 {[%clk 0:01:08.9]} 39. Qf2 {[%clk 0:01:24.2]} 39... Qxf2+ {[%clk 0:01:06.8]} 40. Kxf2 {[%clk 0:01:24.1]} 40... Kf4 {[%clk 0:01:06.1]} 41. Rxh7 {[%clk 0:01:11.5]} 41... e3+ {[%clk 0:01:06]} 42. Ke1 {[%clk 0:01:10]} 42... f2+ {[%clk 0:01:02.4]} 0-1\n',
   'time_control': '300',
   'end_time': 1770739689,
   'rated': True,
   'fen': '3r4/1p5R/2p1b2P/p1P5/5k2/PP2p2P/5p2/4KB2 w - - 0 43',
   'time_class': 'blitz',
   'rules': 'chess',
   'white': {'rating': 3230,
    'result': 'resigned',
    '@id': 'https://api.chess.com/pub/player/gmwso',
    'username': 'GMWSO',
    'uuid': '50758188-90e9-11e6-8018-000000000000'},
   'black': {'rating': 2691,
    'result': 'win',
    '@id': 'https://api.chess.com/pub/player/gcamachomartinez',
    'username': 'GCamachoMartinez',
    'uuid': 'fdec591c-c7f8-11e7-802e-000000000000'},
   'eco': 'https://www.chess.com/openings/Nimzowitsch-Larsen-Attack-Modern-Variation-2.Bb2-d6',
   'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'},
  {'url': 'https://www.chess.com/game/live/165052787669',

In [19]:
group_data.keys()

dict_keys(['games', 'players'])

In [20]:
group_data['players'].__len__()

404

In [21]:
group_data['games'][0]

{'url': 'https://www.chess.com/game/live/165052787661',
 'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "UmutErdemGunduz"]\n[Black "Hikaru"]\n[Result "0-1"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54"]\n[Timezone "UTC"]\n[ECO "B06"]\n[ECOUrl "https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "2682"]\n[BlackElo "3316"]\n[TimeControl "300"]\n[Termination "Hikaru won on time"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:09:53"]\n[Link "https://www.chess.com/game/live/165052787661"]\n\n1. e4 {[%clk 0:04:59.3]} 1... g6 {[%clk 0:04:34.6]} 2. d4 {[%clk 0:04:57.6]} 2... Bg7 {[%clk 0:04:32.7]} 3. Nf3 {[%clk 0:04:56.6]} 3... a6 {[%clk 0:04:30.3]} 4. c4 {[%clk 0:04:51.4]} 4... d6 {[%clk 0:03:59.5]} 5. Nc3 {[%clk 0:04:50]} 5... Bg4 {[%clk 0:03:58.1]} 6. Be3 {[%clk 0:04:41.8]} 6... Nd7 {[%clk 0:03:53.8]} 7. h3 {[%clk 0:04:36.2]} 7... Bxf3 {[%clk 0:03:52.2]} 8. Qxf3 {[%clk 0:04:36.1]} 8... c5 {[%clk 0:03:45.8]} 9. d5 {[%clk 0:04:11.2]} 9... Ngf6 {[%clk 0:03:36.7]} 10. Qd1 {[%clk 0:04:03.5]} 10... O-O {[%clk 0:03:35.4]} 11. Be2 {[%clk 0:04:01]} 11... b5 {[%clk 0:03:30]} 12. Qc2 {[%clk 0:03:28.4]} 12... bxc4 {[%clk 0:03:14.9]} 13. Bxc4 {[%clk 0:03:28.3]} 13... Qa5 {[%clk 0:02:51.5]} 14. O-O {[%clk 0:03:21.9]} 14... Rfb8 {[%clk 0:02:49.4]} 15. a3 {[%clk 0:03:05.3]} 15... Rb7 {[%clk 0:02:37.2]} 16. Rfb1 {[%clk 0:02:37.7]} 16... Rab8 {[%clk 0:02:27.6]} 17. b4 {[%clk 0:02:23.8]} 17... cxb4 {[%clk 0:02:23.5]} 18. axb4 {[%clk 0:02:23.2]} 18... Qc7 {[%clk 0:02:22.7]} 19. Bxa6 {[%clk 0:02:07.1]} 19... Rxb4 {[%clk 0:02:21.7]} 20. Rxb4 {[%clk 0:01:55]} 20... Rxb4 {[%clk 0:02:21.6]} 21. Bd3 {[%clk 0:01:50.6]} 21... Rb8 {[%clk 0:01:54.4]} 22. Ra7 {[%clk 0:01:47.9]} 22... Qc8 {[%clk 0:01:53.6]} 23. Ba6 {[%clk 0:01:43.4]} 23... Qd8 {[%clk 0:01:51.1]} 24. Nb5 {[%clk 0:01:40.5]} 24... Nc5 {[%clk 0:01:44.3]} 25. Bxc5 {[%clk 0:01:17.2]} 25... dxc5 {[%clk 0:01:44.2]} 26. Qxc5 {[%clk 0:01:16.9]} 26... Nxe4 {[%clk 0:01:42.8]} 27. Qxe7 {[%clk 0:01:12.5]} 27... Qxd5 {[%clk 0:01:19.1]} 28. Bb7 {[%clk 0:00:58.8]} 28... Qd1+ {[%clk 0:00:55]} 29. Kh2 {[%clk 0:00:58.3]} 29... Nd2 {[%clk 0:00:54.5]} 30. Ra8 {[%clk 0:00:31.7]} 30... Nf1+ {[%clk 0:00:51.7]} 31. Kg1 {[%clk 0:00:29.1]} 31... Nd2+ {[%clk 0:00:51.6]} 32. Kh2 {[%clk 0:00:28.3]} 32... Rxa8 {[%clk 0:00:51.3]} 33. Bxa8 {[%clk 0:00:27.2]} 33... Nf1+ {[%clk 0:00:50.9]} 34. Kg1 {[%clk 0:00:25.9]} 34... Nd2+ {[%clk 0:00:50.8]} 35. Kh2 {[%clk 0:00:25.3]} 35... Bf8 {[%clk 0:00:50.7]} 36. Qe8 {[%clk 0:00:19.5]} 36... Nf1+ {[%clk 0:00:49.9]} 37. Kg1 {[%clk 0:00:18.9]} 37... Ne3+ {[%clk 0:00:41.5]} 38. Kh2 {[%clk 0:00:17.8]} 38... Nf5 {[%clk 0:00:41.4]} 39. Bf3 {[%clk 0:00:14.4]} 39... Qd2 {[%clk 0:00:38.3]} 40. Qe2 {[%clk 0:00:12.5]} 40... Qb4 {[%clk 0:00:35.9]} 41. g3 {[%clk 0:00:11.8]} 41... h5 {[%clk 0:00:34.4]} 42. Kg2 {[%clk 0:00:11.3]} 42... h4 {[%clk 0:00:33.3]} 43. g4 {[%clk 0:00:10.9]} 43... Ng7 {[%clk 0:00:33]} 44. Bd5 {[%clk 0:00:09.9]} 44... Qc5 {[%clk 0:00:32.1]} 45. Qc4 {[%clk 0:00:09]} 45... Qe7 {[%clk 0:00:31.2]} 46. Nd4 {[%clk 0:00:06.8]} 46... Ne8 {[%clk 0:00:30]} 47. Nf3 {[%clk 0:00:06.2]} 47... Nf6 {[%clk 0:00:28.4]} 48. Ng5 {[%clk 0:00:04.5]} 48... Qe5 {[%clk 0:00:26.7]} 49. Bxf7+ {[%clk 0:00:03.6]} 49... Kg7 {[%clk 0:00:26.4]} 50. Ne6+ {[%clk 0:00:02.4]} 50... Kxf7 {[%clk 0:00:24.7]} 51. Ng5+ {[%clk 0:00:01.3]} 51... Ke7 {[%clk 0:00:24]} 52. Qf7+ {[%clk 0:00:00.9]} 52... Kd6 {[%clk 0:00:23.6]} 53. Qxf8+ {[%clk 0:00:00.3]} 53... Kc6 {[%clk 0:00:23.3]} 0-1\n',
 'time_control': '300',
 'end_time': 1770739793,
 'rated': True,
 'fen': '5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54',
 'time_class': 'blitz',
 'rules': 'chess',
 'white': {'rating': 2682,
  'result': 'timeout',
  '@id': 'https://api.chess.com/pub/player/umuterdemgunduz',
  'username': 'UmutErdemGunduz',
  'uuid': '0016479a-a347-11e9-b619-7d5b9e8b8800'},
 'black': {'rating': 3316,
  'result': 'win',
  '@id': 'https://api.chess.com/pub/player/hikaru',
  'username': 'Hikaru',
  'uuid': '6f4deb88-7718-11e3-8016-000000000000'},
 'eco': 'https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3',
 'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'}

In [22]:
tournament_players = []       
for x in tournament['players']:
    if x['username'] not in tournament_players:
        tournament_players.append(x['username'])
        
round_players= []
for x in round_data['players']:
    if x['username'] not in round_players:
        round_players.append(x['username'])
print("Players in round:", len(round_players))

print("Players in tournament:", len(tournament_players))
print("\nTournament players missing players in round:")
print(len(set(round_players) - set(tournament_players)))
print("Viceversa, missing players in tournament:")
print(len(set(tournament_players) - set(round_players)))

Players in round: 404
Players in tournament: 25

Tournament players missing players in round:
379
Viceversa, missing players in tournament:
0

In [23]:
groups = round_data['groups']
group = groups[0]
group_response = urlopen(group, timeout=30)
group_data = json.load(group_response)
group_data.keys()

dict_keys(['games', 'players'])

In [24]:
group_data.keys()

dict_keys(['games', 'players'])

In [25]:
group_data['players'].__len__()

404

In [26]:
group_data['games']

[{'url': 'https://www.chess.com/game/live/165052787661',
  'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "UmutErdemGunduz"]\n[Black "Hikaru"]\n[Result "0-1"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54"]\n[Timezone "UTC"]\n[ECO "B06"]\n[ECOUrl "https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "2682"]\n[BlackElo "3316"]\n[TimeControl "300"]\n[Termination "Hikaru won on time"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:09:53"]\n[Link "https://www.chess.com/game/live/165052787661"]\n\n1. e4 {[%clk 0:04:59.3]} 1... g6 {[%clk 0:04:34.6]} 2. d4 {[%clk 0:04:57.6]} 2... Bg7 {[%clk 0:04:32.7]} 3. Nf3 {[%clk 0:04:56.6]} 3... a6 {[%clk 0:04:30.3]} 4. c4 {[%clk 0:04:51.4]} 4... d6 {[%clk 0:03:59.5]} 5. Nc3 {[%clk 0:04:50]} 5... Bg4 {[%clk 0:03:58.1]} 6. Be3 {[%clk 0:04:41.8]} 6... Nd7 {[%clk 0:03:53.8]} 7. h3 {[%clk 0:04:36.2]} 7... Bxf3 {[%clk 0:03:52.2]} 8. Qxf3 {[%clk 0:04:36.1]} 8... c5 {[%clk 0:03:45.8]} 9. d5 {[%clk 0:04:11.2]} 9... Ngf6 {[%clk 0:03:36.7]} 10. Qd1 {[%clk 0:04:03.5]} 10... O-O {[%clk 0:03:35.4]} 11. Be2 {[%clk 0:04:01]} 11... b5 {[%clk 0:03:30]} 12. Qc2 {[%clk 0:03:28.4]} 12... bxc4 {[%clk 0:03:14.9]} 13. Bxc4 {[%clk 0:03:28.3]} 13... Qa5 {[%clk 0:02:51.5]} 14. O-O {[%clk 0:03:21.9]} 14... Rfb8 {[%clk 0:02:49.4]} 15. a3 {[%clk 0:03:05.3]} 15... Rb7 {[%clk 0:02:37.2]} 16. Rfb1 {[%clk 0:02:37.7]} 16... Rab8 {[%clk 0:02:27.6]} 17. b4 {[%clk 0:02:23.8]} 17... cxb4 {[%clk 0:02:23.5]} 18. axb4 {[%clk 0:02:23.2]} 18... Qc7 {[%clk 0:02:22.7]} 19. Bxa6 {[%clk 0:02:07.1]} 19... Rxb4 {[%clk 0:02:21.7]} 20. Rxb4 {[%clk 0:01:55]} 20... Rxb4 {[%clk 0:02:21.6]} 21. Bd3 {[%clk 0:01:50.6]} 21... Rb8 {[%clk 0:01:54.4]} 22. Ra7 {[%clk 0:01:47.9]} 22... Qc8 {[%clk 0:01:53.6]} 23. Ba6 {[%clk 0:01:43.4]} 23... Qd8 {[%clk 0:01:51.1]} 24. Nb5 {[%clk 0:01:40.5]} 24... Nc5 {[%clk 0:01:44.3]} 25. Bxc5 {[%clk 0:01:17.2]} 25... dxc5 {[%clk 0:01:44.2]} 26. Qxc5 {[%clk 0:01:16.9]} 26... Nxe4 {[%clk 0:01:42.8]} 27. Qxe7 {[%clk 0:01:12.5]} 27... Qxd5 {[%clk 0:01:19.1]} 28. Bb7 {[%clk 0:00:58.8]} 28... Qd1+ {[%clk 0:00:55]} 29. Kh2 {[%clk 0:00:58.3]} 29... Nd2 {[%clk 0:00:54.5]} 30. Ra8 {[%clk 0:00:31.7]} 30... Nf1+ {[%clk 0:00:51.7]} 31. Kg1 {[%clk 0:00:29.1]} 31... Nd2+ {[%clk 0:00:51.6]} 32. Kh2 {[%clk 0:00:28.3]} 32... Rxa8 {[%clk 0:00:51.3]} 33. Bxa8 {[%clk 0:00:27.2]} 33... Nf1+ {[%clk 0:00:50.9]} 34. Kg1 {[%clk 0:00:25.9]} 34... Nd2+ {[%clk 0:00:50.8]} 35. Kh2 {[%clk 0:00:25.3]} 35... Bf8 {[%clk 0:00:50.7]} 36. Qe8 {[%clk 0:00:19.5]} 36... Nf1+ {[%clk 0:00:49.9]} 37. Kg1 {[%clk 0:00:18.9]} 37... Ne3+ {[%clk 0:00:41.5]} 38. Kh2 {[%clk 0:00:17.8]} 38... Nf5 {[%clk 0:00:41.4]} 39. Bf3 {[%clk 0:00:14.4]} 39... Qd2 {[%clk 0:00:38.3]} 40. Qe2 {[%clk 0:00:12.5]} 40... Qb4 {[%clk 0:00:35.9]} 41. g3 {[%clk 0:00:11.8]} 41... h5 {[%clk 0:00:34.4]} 42. Kg2 {[%clk 0:00:11.3]} 42... h4 {[%clk 0:00:33.3]} 43. g4 {[%clk 0:00:10.9]} 43... Ng7 {[%clk 0:00:33]} 44. Bd5 {[%clk 0:00:09.9]} 44... Qc5 {[%clk 0:00:32.1]} 45. Qc4 {[%clk 0:00:09]} 45... Qe7 {[%clk 0:00:31.2]} 46. Nd4 {[%clk 0:00:06.8]} 46... Ne8 {[%clk 0:00:30]} 47. Nf3 {[%clk 0:00:06.2]} 47... Nf6 {[%clk 0:00:28.4]} 48. Ng5 {[%clk 0:00:04.5]} 48... Qe5 {[%clk 0:00:26.7]} 49. Bxf7+ {[%clk 0:00:03.6]} 49... Kg7 {[%clk 0:00:26.4]} 50. Ne6+ {[%clk 0:00:02.4]} 50... Kxf7 {[%clk 0:00:24.7]} 51. Ng5+ {[%clk 0:00:01.3]} 51... Ke7 {[%clk 0:00:24]} 52. Qf7+ {[%clk 0:00:00.9]} 52... Kd6 {[%clk 0:00:23.6]} 53. Qxf8+ {[%clk 0:00:00.3]} 53... Kc6 {[%clk 0:00:23.3]} 0-1\n',
  'time_control': '300',
  'end_time': 1770739793,
  'rated': True,
  'fen': '5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54',
  'time_class': 'blitz',
  'rules': 'chess',
  'white': {'rating': 2682,
   'result': 'timeout',
   '@id': 'https://api.chess.com/pub/player/umuterdemgunduz',
   'username': 'UmutErdemGunduz',
   'uuid': '0016479a-a347-11e9-b619-7d5b9e8b8800'},
  'black': {'rating': 3316,
   'result': 'win',
   '@id': 'https://api.chess.com/pub/player/hikaru',
   'username': 'Hikaru',
   'uuid': '6f4deb88-7718-11e3-8016-000000000000'},
  'eco': 'https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3',
  'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'},
 {'url': 'https://www.chess.com/game/live/165052787663',
  'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "lachesisQ"]\n[Black "GorinDeshi"]\n[Result "1-0"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "3r1k2/p1R1p2b/4N3/4R3/P5p1/1P4P1/2P4r/2K5 b - - 2 35"]\n[Timezone "UTC"]\n[ECO "B76"]\n[ECOUrl "https://www.chess.com/openings/Sicilian-Defense-Open-Dragon-Rauzer-Variation-9...d5-10.Nxc6-bxc6-11.Bh6"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "3279"]\n[BlackElo "2678"]\n[TimeControl "300"]\n[Termination "lachesisQ won by resignation"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:06:37"]\n[Link "https://www.chess.com/game/live/165052787663"]\n\n1. e4 {[%clk 0:04:59.9]} 1... c5 {[%clk 0:04:58.4]} 2. Nf3 {[%clk 0:04:58.5]} 2... d6 {[%clk 0:04:56]} 3. d4 {[%clk 0:04:57.9]} 3... cxd4 {[%clk 0:04:55.9]} 4. Nxd4 {[%clk 0:04:57.8]} 4... Nf6 {[%clk 0:04:55]} 5. Nc3 {[%clk 0:04:57.6]} 5... g6 {[%clk 0:04:53.8]} 6. Be3 {[%clk 0:04:54.5]} 6... Bg7 {[%clk 0:04:53.1]} 7. f3 {[%clk 0:04:54]} 7... O-O {[%clk 0:04:52.2]} 8. Qd2 {[%clk 0:04:53.7]} 8... Nc6 {[%clk 0:04:51.5]} 9. O-O-O {[%clk 0:04:53.4]} 9... d5 {[%clk 0:04:50.8]} 10. Nxc6 {[%clk 0:04:52.8]} 10... bxc6 {[%clk 0:04:47.5]} 11. Bh6 {[%clk 0:04:52.5]} 11... Be6 {[%clk 0:04:14.4]} 12. h4 {[%clk 0:04:48.5]} 12... dxe4 {[%clk 0:04:11.2]} 13. Bxg7 {[%clk 0:04:20.9]} 13... Qxd2+ {[%clk 0:04:02.4]} 14. Rxd2 {[%clk 0:04:20.8]} 14... Kxg7 {[%clk 0:04:01.7]} 15. fxe4 {[%clk 0:04:15.2]} 15... Rfd8 {[%clk 0:03:55.4]} 16. Be2 {[%clk 0:04:14.4]} 16... h5 {[%clk 0:03:30.7]} 17. b3 {[%clk 0:04:10.4]} 17... Ng4 {[%clk 0:03:24.9]} 18. Bxg4 {[%clk 0:04:08.1]} 18... hxg4 {[%clk 0:03:23.5]} 19. g3 {[%clk 0:04:07.3]} 19... Kf6 {[%clk 0:03:07.3]} 20. Rhd1 {[%clk 0:04:05.6]} 20... Rh8 {[%clk 0:02:59.3]} 21. Ne2 {[%clk 0:04:03.3]} 21... g5 {[%clk 0:02:55.7]} 22. hxg5+ {[%clk 0:03:50]} 22... Kxg5 {[%clk 0:02:54.7]} 23. Nd4 {[%clk 0:03:49.5]} 23... Rh3 {[%clk 0:02:44]} 24. Rd3 {[%clk 0:03:47.4]} 24... Bd7 {[%clk 0:02:36.5]} 25. Ne2 {[%clk 0:03:42.9]} 25... Be6 {[%clk 0:02:21.4]} 26. Rc3 {[%clk 0:03:41.7]} 26... Rh2 {[%clk 0:01:54.5]} 27. Nf4 {[%clk 0:03:40.3]} 27... Bc8 {[%clk 0:01:33.6]} 28. Rc5+ {[%clk 0:03:36.2]} 28... f5 {[%clk 0:01:25.1]} 29. exf5 {[%clk 0:03:33]} 29... Bxf5 {[%clk 0:01:21.1]} 30. Re1 {[%clk 0:03:32.5]} 30... Kf6 {[%clk 0:01:09.9]} 31. Rxc6+ {[%clk 0:03:28.7]} 31... Kf7 {[%clk 0:01:03.2]} 32. Rc7 {[%clk 0:03:27.6]} 32... Kf8 {[%clk 0:00:58.6]} 33. Re5 {[%clk 0:03:22.8]} 33... Bh7 {[%clk 0:00:47.1]} 34. a4 {[%clk 0:03:06.6]} 34... Rd8 {[%clk 0:00:37.8]} 35. Ne6+ {[%clk 0:03:05.5]} 1-0\n',
  'time_control': '300',
  'end_time': 1770739597,
  'rated': True,
  'fen': '3r1k2/p1R1p2b/4N3/4R3/P5p1/1P4P1/2P4r/2K5 b - - 2 35',
  'time_class': 'blitz',
  'rules': 'chess',
  'white': {'rating': 3279,
   'result': 'win',
   '@id': 'https://api.chess.com/pub/player/lachesisq',
   'username': 'lachesisQ',
   'uuid': 'ea103016-2647-11e6-8040-000000000000'},
  'black': {'rating': 2678,
   'result': 'resigned',
   '@id': 'https://api.chess.com/pub/player/gorindeshi',
   'username': 'GorinDeshi',
   'uuid': 'af27c69c-36ef-11ee-afee-879979d51b45'},
  'eco': 'https://www.chess.com/openings/Sicilian-Defense-Open-Dragon-Rauzer-Variation-9...d5-10.Nxc6-bxc6-11.Bh6',
  'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'},
 {'url': 'https://www.chess.com/game/live/165052787665',
  'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "JaiSankarS"]\n[Black "NikoTheodorou"]\n[Result "0-1"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "8/8/6k1/5p2/5PK1/6P1/8/7q w - f6 0 55"]\n[Timezone "UTC"]\n[ECO "A15"]\n[ECOUrl "https://www.chess.com/openings/English-Opening-Anglo-Indian-Kings-Knight-Queens-Indian-Formation...6.O-O-O-O-7.Nc3-Ne4"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "2677"]\n[BlackElo "3252"]\n[TimeControl "300"]\n[Termination "NikoTheodorou won by checkmate"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:06:42"]\n[Link "https://www.chess.com/game/live/165052787665"]\n\n1. Nf3 {[%clk 0:04:59.6]} 1... Nf6 {[%clk 0:04:58.9]} 2. g3 {[%clk 0:04:56.1]} 2... b6 {[%clk 0:04:57.8]} 3. Bg2 {[%clk 0:04:56]} 3... Bb7 {[%clk 0:04:57.7]} 4. O-O {[%clk 0:04:55.9]} 4... g6 {[%clk 0:04:57.3]} 5. c4 {[%clk 0:04:54.3]} 5... Bg7 {[%clk 0:04:56.5]} 6. Nc3 {[%clk 0:04:54.2]} 6... O-O {[%clk 0:04:55.9]} 7. d4 {[%clk 0:04:53.8]} 7... Ne4 {[%clk 0:04:55.4]} 8. Bf4 {[%clk 0:04:50]} 8... Nxc3 {[%clk 0:04:46.5]} 9. bxc3 {[%clk 0:04:49.9]} 9... Nc6 {[%clk 0:04:46.2]} 10. Ne5 {[%clk 0:04:45.6]} 10... Na5 {[%clk 0:04:40.2]} 11. Bxb7 {[%clk 0:04:39.5]} 11... Nxb7 {[%clk 0:04:40.1]} 12. Qd2 {[%clk 0:04:39.3]} 12... Na5 {[%clk 0:04:38.2]} 13. c5 {[%clk 0:04:34.2]} 13... d6 {[%clk 0:04:29.2]} 14. cxd6 {[%clk 0:04:33.3]} 14... cxd6 {[%clk 0:04:29.1]} 15. Nf3 {[%clk 0:04:30.2]} 15... Rc8 {[%clk 0:04:28.2]} 16. Rfc1 {[%clk 0:04:28.4]} 16... Nc4 {[%clk 0:04:19.5]} 17. Qd3 {[%clk 0:04:23.6]} 17... Qd7 {[%clk 0:04:18.9]} 18. a4 {[%clk 0:04:17.6]} 18... Rc7 {[%clk 0:04:15.1]} 19. Nd2 {[%clk 0:04:15.1]} 19... Rfc8 {[%clk 0:04:12.5]} 20. Nxc4 {[%clk 0:04:13.4]} 20... Rxc4 {[%clk 0:04:12.4]} 21. Bd2 {[%clk 0:04:12.7]} 21... Rxa4 {[%clk 0:04:10.3]} 22. c4 {[%clk 0:04:07.5]} 22... Rcxc4 {[%clk 0:03:57.2]} 23. Qxc4 {[%clk 0:04:04.2]} 23... Rxc4 {[%clk 0:03:55.9]} 24. Rxc4 {[%clk 0:04:04.1]} 24... h5 {[%clk 0:03:21.9]} 25. Rac1 {[%clk 0:04:00.6]} 25... Bf6 {[%clk 0:03:13.5]} 26. d5 {[%clk 0:03:49.7]} 26... Kg7 {[%clk 0:03:07.7]} 27. e4 {[%clk 0:03:47.7]} 27... h4 {[%clk 0:03:05]} 28. Be3 {[%clk 0:03:38.1]} 28... h3 {[%clk 0:02:58.9]} 29. f3 {[%clk 0:03:36.6]} 29... Qb5 {[%clk 0:02:54.4]} 30. Kf2 {[%clk 0:03:33.1]} 30... Qb2+ {[%clk 0:02:49]} 31. R4c2 {[%clk 0:03:31.1]} 31... Qb3 {[%clk 0:02:47.9]} 32. Rc7 {[%clk 0:03:24.1]} 32... a5 {[%clk 0:02:45.3]} 33. f4 {[%clk 0:03:16.5]} 33... Qd3 {[%clk 0:02:40.5]} 34. Kf3 {[%clk 0:03:04.6]} 34... Bd4 {[%clk 0:02:39.6]} 35. Re1 {[%clk 0:03:02.6]} 35... a4 {[%clk 0:02:17.2]} 36. Rxe7 {[%clk 0:02:54.9]} 36... a3 {[%clk 0:02:13.7]} 37. e5 {[%clk 0:02:50.1]} 37... Bxe3 {[%clk 0:02:09.6]} 38. Rxe3 {[%clk 0:02:48.1]} 38... Qxd5+ {[%clk 0:01:59.4]} 39. Kg4 {[%clk 0:02:47.6]} 39... a2 {[%clk 0:01:58.9]} 40. Ra7 {[%clk 0:02:39.6]} 40... Qd1+ {[%clk 0:01:56.8]} 41. Kxh3 {[%clk 0:02:37.6]} 41... a1=Q {[%clk 0:01:56]} 42. Rxa1 {[%clk 0:02:35.6]} 42... Qxa1 {[%clk 0:01:55.9]} 43. exd6 {[%clk 0:02:34]} 43... Qd4 {[%clk 0:01:55.1]} 44. Re5 {[%clk 0:02:28.1]} 44... Qxd6 {[%clk 0:01:54.1]} 45. Kg4 {[%clk 0:02:27.8]} 45... b5 {[%clk 0:01:52.9]} 46. h4 {[%clk 0:02:25.9]} 46... b4 {[%clk 0:01:52.1]} 47. h5 {[%clk 0:02:25.2]} 47... b3 {[%clk 0:01:50.9]} 48. hxg6 {[%clk 0:02:23.9]} 48... Qxg6+ {[%clk 0:01:47.3]} 49. Kf3 {[%clk 0:02:21.4]} 49... b2 {[%clk 0:01:46.2]} 50. Re1 {[%clk 0:02:17.7]} 50... b1=Q {[%clk 0:01:44.9]} 51. Rxb1 {[%clk 0:02:17.6]} 51... Qxb1 {[%clk 0:01:44.3]} 52. Kg4 {[%clk 0:02:17.4]} 52... Kg6 {[%clk 0:01:43.3]} 53. Kh4 {[%clk 0:02:15.6]} 53... Qh1+ {[%clk 0:01:42.1]} 54. Kg4 {[%clk 0:02:14.5]} 54... f5# {[%clk 0:01:41.8]} 0-1\n',
  'time_control': '300',
  'end_time': 1770739602,
  'rated': True,
  'fen': '8/8/6k1/5p2/5PK1/6P1/8/7q w - f6 0 55',
  'time_class': 'blitz',
  'rules': 'chess',
  'white': {'rating': 2677,
   'result': 'checkmated',
   '@id': 'https://api.chess.com/pub/player/jaisankars',
   'username': 'JaiSankarS',
   'uuid': 'cb754d68-e4f6-11ef-a68a-9be73e69b3c8'},
  'black': {'rating': 3252,
   'result': 'win',
   '@id': 'https://api.chess.com/pub/player/nikotheodorou',
   'username': 'NikoTheodorou',
   'uuid': '4d8a88c8-4b2b-11eb-89ec-1b7cb3f4e61a'},
  'eco': 'https://www.chess.com/openings/English-Opening-Anglo-Indian-Kings-Knight-Queens-Indian-Formation...6.O-O-O-O-7.Nc3-Ne4',
  'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'},
 {'url': 'https://www.chess.com/game/live/165052787667',
  'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "GMWSO"]\n[Black "GCamachoMartinez"]\n[Result "0-1"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "3r4/1p5R/2p1b2P/p1P5/5k2/PP2p2P/5p2/4KB2 w - - 0 43"]\n[Timezone "UTC"]\n[ECO "A01"]\n[ECOUrl "https://www.chess.com/openings/Nimzowitsch-Larsen-Attack-Modern-Variation-2.Bb2-d6"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "3230"]\n[BlackElo "2691"]\n[TimeControl "300"]\n[Termination "GCamachoMartinez won by resignation"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:08:09"]\n[Link "https://www.chess.com/game/live/165052787667"]\n\n1. b3 {[%clk 0:04:59.9]} 1... e5 {[%clk 0:04:58.1]} 2. Bb2 {[%clk 0:04:56.1]} 2... d6 {[%clk 0:04:57.3]} 3. d4 {[%clk 0:04:47.9]} 3... exd4 {[%clk 0:04:55.8]} 4. Nf3 {[%clk 0:04:46.9]} 4... Nf6 {[%clk 0:04:52.5]} 5. Nxd4 {[%clk 0:04:43.9]} 5... g6 {[%clk 0:04:50.7]} 6. c4 {[%clk 0:04:40.4]} 6... Bg7 {[%clk 0:04:49.7]} 7. g3 {[%clk 0:04:39.1]} 7... O-O {[%clk 0:04:48.6]} 8. Bg2 {[%clk 0:04:38.5]} 8... Re8 {[%clk 0:04:35.7]} 9. O-O {[%clk 0:04:36.3]} 9... Nbd7 {[%clk 0:04:34.7]} 10. Nc3 {[%clk 0:04:30.2]} 10... Nc5 {[%clk 0:04:29.5]} 11. Qc2 {[%clk 0:04:24.8]} 11... a5 {[%clk 0:04:19.6]} 12. Rad1 {[%clk 0:04:23.6]} 12... c6 {[%clk 0:04:15.6]} 13. a3 {[%clk 0:04:15.7]} 13... Qc7 {[%clk 0:04:07.2]} 14. Rd2 {[%clk 0:04:08.9]} 14... Bd7 {[%clk 0:03:54.3]} 15. Rfd1 {[%clk 0:04:05.6]} 15... Rad8 {[%clk 0:03:53.9]} 16. h3 {[%clk 0:03:58.8]} 16... Ne6 {[%clk 0:03:50.5]} 17. Nf3 {[%clk 0:03:56.2]} 17... Bc8 {[%clk 0:03:48]} 18. Kh2 {[%clk 0:03:53]} 18... Nc5 {[%clk 0:03:45.3]} 19. Nd4 {[%clk 0:03:46.7]} 19... Ne6 {[%clk 0:03:44]} 20. e3 {[%clk 0:03:42.7]} 20... Nxd4 {[%clk 0:03:41.9]} 21. Rxd4 {[%clk 0:03:42.3]} 21... Bf5 {[%clk 0:03:23.2]} 22. e4 {[%clk 0:03:31.1]} 22... Be6 {[%clk 0:03:03.3]} 23. f4 {[%clk 0:03:28.7]} 23... Nh5 {[%clk 0:02:49.5]} 24. R4d3 {[%clk 0:03:21.2]} 24... f5 {[%clk 0:02:48.6]} 25. Re3 {[%clk 0:03:12.2]} 25... g5 {[%clk 0:02:38.7]} 26. exf5 {[%clk 0:03:08.7]} 26... Bf7 {[%clk 0:02:25.7]} 27. Rxe8+ {[%clk 0:02:59.7]} 27... Rxe8 {[%clk 0:02:25.6]} 28. Ne4 {[%clk 0:02:58.2]} 28... gxf4 {[%clk 0:02:14.1]} 29. g4 {[%clk 0:02:50.5]} 29... f3 {[%clk 0:02:08.8]} 30. gxh5 {[%clk 0:02:36.1]} 30... d5+ {[%clk 0:02:02.5]} 31. Kg1 {[%clk 0:02:20.6]} 31... dxe4 {[%clk 0:02:01.3]} 32. Bxg7 {[%clk 0:02:20.1]} 32... Kxg7 {[%clk 0:02:00.3]} 33. h6+ {[%clk 0:02:06]} 33... Kf6 {[%clk 0:01:54.4]} 34. c5 {[%clk 0:01:47.3]} 34... Qg3 {[%clk 0:01:37.7]} 35. Rd6+ {[%clk 0:01:40.6]} 35... Kxf5 {[%clk 0:01:35.1]} 36. Rd7 {[%clk 0:01:40.1]} 36... Be6 {[%clk 0:01:21.7]} 37. Rg7 {[%clk 0:01:37.1]} 37... Qe1+ {[%clk 0:01:13.7]} 38. Bf1 {[%clk 0:01:34.5]} 38... Rd8 {[%clk 0:01:08.9]} 39. Qf2 {[%clk 0:01:24.2]} 39... Qxf2+ {[%clk 0:01:06.8]} 40. Kxf2 {[%clk 0:01:24.1]} 40... Kf4 {[%clk 0:01:06.1]} 41. Rxh7 {[%clk 0:01:11.5]} 41... e3+ {[%clk 0:01:06]} 42. Ke1 {[%clk 0:01:10]} 42... f2+ {[%clk 0:01:02.4]} 0-1\n',
  'time_control': '300',
  'end_time': 1770739689,
  'rated': True,
  'fen': '3r4/1p5R/2p1b2P/p1P5/5k2/PP2p2P/5p2/4KB2 w - - 0 43',
  'time_class': 'blitz',
  'rules': 'chess',
  'white': {'rating': 3230,
   'result': 'resigned',
   '@id': 'https://api.chess.com/pub/player/gmwso',
   'username': 'GMWSO',
   'uuid': '50758188-90e9-11e6-8018-000000000000'},
  'black': {'rating': 2691,
   'result': 'win',
   '@id': 'https://api.chess.com/pub/player/gcamachomartinez',
   'username': 'GCamachoMartinez',
   'uuid': 'fdec591c-c7f8-11e7-802e-000000000000'},
  'eco': 'https://www.chess.com/openings/Nimzowitsch-Larsen-Attack-Modern-Variation-2.Bb2-d6',
  'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'},
 {'url': 'https://www.chess.com/game/live/165052787669',

In [27]:
len(group_data['games'])

202

In [28]:
group_data['games'][0]

{'url': 'https://www.chess.com/game/live/165052787661',
 'pgn': '[Event "Live Chess"]\n[Site "Chess.com"]\n[Date "2026.02.10"]\n[Round "-"]\n[White "UmutErdemGunduz"]\n[Black "Hikaru"]\n[Result "0-1"]\n[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]\n[CurrentPosition "5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54"]\n[Timezone "UTC"]\n[ECO "B06"]\n[ECOUrl "https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3"]\n[UTCDate "2026.02.10"]\n[UTCTime "16:00:00"]\n[WhiteElo "2682"]\n[BlackElo "3316"]\n[TimeControl "300"]\n[Termination "Hikaru won on time"]\n[StartTime "16:00:00"]\n[EndDate "2026.02.10"]\n[EndTime "16:09:53"]\n[Link "https://www.chess.com/game/live/165052787661"]\n\n1. e4 {[%clk 0:04:59.3]} 1... g6 {[%clk 0:04:34.6]} 2. d4 {[%clk 0:04:57.6]} 2... Bg7 {[%clk 0:04:32.7]} 3. Nf3 {[%clk 0:04:56.6]} 3... a6 {[%clk 0:04:30.3]} 4. c4 {[%clk 0:04:51.4]} 4... d6 {[%clk 0:03:59.5]} 5. Nc3 {[%clk 0:04:50]} 5... Bg4 {[%clk 0:03:58.1]} 6. Be3 {[%clk 0:04:41.8]} 6... Nd7 {[%clk 0:03:53.8]} 7. h3 {[%clk 0:04:36.2]} 7... Bxf3 {[%clk 0:03:52.2]} 8. Qxf3 {[%clk 0:04:36.1]} 8... c5 {[%clk 0:03:45.8]} 9. d5 {[%clk 0:04:11.2]} 9... Ngf6 {[%clk 0:03:36.7]} 10. Qd1 {[%clk 0:04:03.5]} 10... O-O {[%clk 0:03:35.4]} 11. Be2 {[%clk 0:04:01]} 11... b5 {[%clk 0:03:30]} 12. Qc2 {[%clk 0:03:28.4]} 12... bxc4 {[%clk 0:03:14.9]} 13. Bxc4 {[%clk 0:03:28.3]} 13... Qa5 {[%clk 0:02:51.5]} 14. O-O {[%clk 0:03:21.9]} 14... Rfb8 {[%clk 0:02:49.4]} 15. a3 {[%clk 0:03:05.3]} 15... Rb7 {[%clk 0:02:37.2]} 16. Rfb1 {[%clk 0:02:37.7]} 16... Rab8 {[%clk 0:02:27.6]} 17. b4 {[%clk 0:02:23.8]} 17... cxb4 {[%clk 0:02:23.5]} 18. axb4 {[%clk 0:02:23.2]} 18... Qc7 {[%clk 0:02:22.7]} 19. Bxa6 {[%clk 0:02:07.1]} 19... Rxb4 {[%clk 0:02:21.7]} 20. Rxb4 {[%clk 0:01:55]} 20... Rxb4 {[%clk 0:02:21.6]} 21. Bd3 {[%clk 0:01:50.6]} 21... Rb8 {[%clk 0:01:54.4]} 22. Ra7 {[%clk 0:01:47.9]} 22... Qc8 {[%clk 0:01:53.6]} 23. Ba6 {[%clk 0:01:43.4]} 23... Qd8 {[%clk 0:01:51.1]} 24. Nb5 {[%clk 0:01:40.5]} 24... Nc5 {[%clk 0:01:44.3]} 25. Bxc5 {[%clk 0:01:17.2]} 25... dxc5 {[%clk 0:01:44.2]} 26. Qxc5 {[%clk 0:01:16.9]} 26... Nxe4 {[%clk 0:01:42.8]} 27. Qxe7 {[%clk 0:01:12.5]} 27... Qxd5 {[%clk 0:01:19.1]} 28. Bb7 {[%clk 0:00:58.8]} 28... Qd1+ {[%clk 0:00:55]} 29. Kh2 {[%clk 0:00:58.3]} 29... Nd2 {[%clk 0:00:54.5]} 30. Ra8 {[%clk 0:00:31.7]} 30... Nf1+ {[%clk 0:00:51.7]} 31. Kg1 {[%clk 0:00:29.1]} 31... Nd2+ {[%clk 0:00:51.6]} 32. Kh2 {[%clk 0:00:28.3]} 32... Rxa8 {[%clk 0:00:51.3]} 33. Bxa8 {[%clk 0:00:27.2]} 33... Nf1+ {[%clk 0:00:50.9]} 34. Kg1 {[%clk 0:00:25.9]} 34... Nd2+ {[%clk 0:00:50.8]} 35. Kh2 {[%clk 0:00:25.3]} 35... Bf8 {[%clk 0:00:50.7]} 36. Qe8 {[%clk 0:00:19.5]} 36... Nf1+ {[%clk 0:00:49.9]} 37. Kg1 {[%clk 0:00:18.9]} 37... Ne3+ {[%clk 0:00:41.5]} 38. Kh2 {[%clk 0:00:17.8]} 38... Nf5 {[%clk 0:00:41.4]} 39. Bf3 {[%clk 0:00:14.4]} 39... Qd2 {[%clk 0:00:38.3]} 40. Qe2 {[%clk 0:00:12.5]} 40... Qb4 {[%clk 0:00:35.9]} 41. g3 {[%clk 0:00:11.8]} 41... h5 {[%clk 0:00:34.4]} 42. Kg2 {[%clk 0:00:11.3]} 42... h4 {[%clk 0:00:33.3]} 43. g4 {[%clk 0:00:10.9]} 43... Ng7 {[%clk 0:00:33]} 44. Bd5 {[%clk 0:00:09.9]} 44... Qc5 {[%clk 0:00:32.1]} 45. Qc4 {[%clk 0:00:09]} 45... Qe7 {[%clk 0:00:31.2]} 46. Nd4 {[%clk 0:00:06.8]} 46... Ne8 {[%clk 0:00:30]} 47. Nf3 {[%clk 0:00:06.2]} 47... Nf6 {[%clk 0:00:28.4]} 48. Ng5 {[%clk 0:00:04.5]} 48... Qe5 {[%clk 0:00:26.7]} 49. Bxf7+ {[%clk 0:00:03.6]} 49... Kg7 {[%clk 0:00:26.4]} 50. Ne6+ {[%clk 0:00:02.4]} 50... Kxf7 {[%clk 0:00:24.7]} 51. Ng5+ {[%clk 0:00:01.3]} 51... Ke7 {[%clk 0:00:24]} 52. Qf7+ {[%clk 0:00:00.9]} 52... Kd6 {[%clk 0:00:23.6]} 53. Qxf8+ {[%clk 0:00:00.3]} 53... Kc6 {[%clk 0:00:23.3]} 0-1\n',
 'time_control': '300',
 'end_time': 1770739793,
 'rated': True,
 'fen': '5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54',
 'time_class': 'blitz',
 'rules': 'chess',
 'white': {'rating': 2682,
  'result': 'timeout',
  '@id': 'https://api.chess.com/pub/player/umuterdemgunduz',
  'username': 'UmutErdemGunduz',
  'uuid': '0016479a-a347-11e9-b619-7d5b9e8b8800'},
 'black': {'rating': 3316,
  'result': 'win',
  '@id': 'https://api.chess.com/pub/player/hikaru',
  'username': 'Hikaru',
  'uuid': '6f4deb88-7718-11e3-8016-000000000000'},
 'eco': 'https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3',
 'tournament': 'https://api.chess.com/pub/tournament/titled-tuesday-blitz-february-10-2026-6221327'}

In [29]:
group_data['games'][0].keys()

dict_keys(['url', 'pgn', 'time_control', 'end_time', 'rated', 'fen', 'time_class', 'rules', 'white', 'black', 'eco', 'tournament'])

In [30]:
group_data['games'][0]['white']

{'rating': 2682,
 'result': 'timeout',
 '@id': 'https://api.chess.com/pub/player/umuterdemgunduz',
 'username': 'UmutErdemGunduz',
 'uuid': '0016479a-a347-11e9-b619-7d5b9e8b8800'}

In [31]:
group_data['games'][0]['black']

{'rating': 3316,
 'result': 'win',
 '@id': 'https://api.chess.com/pub/player/hikaru',
 'username': 'Hikaru',
 'uuid': '6f4deb88-7718-11e3-8016-000000000000'}

In [32]:
group_data['games'][0]['pgn'].split("\n")

['[Event "Live Chess"]',
 '[Site "Chess.com"]',
 '[Date "2026.02.10"]',
 '[Round "-"]',
 '[White "UmutErdemGunduz"]',
 '[Black "Hikaru"]',
 '[Result "0-1"]',
 '[Tournament "https://www.chess.com/tournament/live/titled-tuesday-blitz-february-10-2026-6221327"]',
 '[CurrentPosition "5Q2/8/2k2np1/4q1N1/6Pp/7P/5PK1/8 w - - 1 54"]',
 '[Timezone "UTC"]',
 '[ECO "B06"]',
 '[ECOUrl "https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d4-Bg7-3.Nf3"]',
 '[UTCDate "2026.02.10"]',
 '[UTCTime "16:00:00"]',
 '[WhiteElo "2682"]',
 '[BlackElo "3316"]',
 '[TimeControl "300"]',
 '[Termination "Hikaru won on time"]',
 '[StartTime "16:00:00"]',
 '[EndDate "2026.02.10"]',
 '[EndTime "16:09:53"]',
 '[Link "https://www.chess.com/game/live/165052787661"]',
 '',
 '1. e4 {[%clk 0:04:59.3]} 1... g6 {[%clk 0:04:34.6]} 2. d4 {[%clk 0:04:57.6]} 2... Bg7 {[%clk 0:04:32.7]} 3. Nf3 {[%clk 0:04:56.6]} 3... a6 {[%clk 0:04:30.3]} 4. c4 {[%clk 0:04:51.4]} 4... d6 {[%clk 0:03:59.5]} 5. Nc3 {[%clk 0:04:50]} 5... Bg4 {[%clk 0:03:58.1]} 6. Be3 {[%clk 0:04:41.8]} 6... Nd7 {[%clk 0:03:53.8]} 7. h3 {[%clk 0:04:36.2]} 7... Bxf3 {[%clk 0:03:52.2]} 8. Qxf3 {[%clk 0:04:36.1]} 8... c5 {[%clk 0:03:45.8]} 9. d5 {[%clk 0:04:11.2]} 9... Ngf6 {[%clk 0:03:36.7]} 10. Qd1 {[%clk 0:04:03.5]} 10... O-O {[%clk 0:03:35.4]} 11. Be2 {[%clk 0:04:01]} 11... b5 {[%clk 0:03:30]} 12. Qc2 {[%clk 0:03:28.4]} 12... bxc4 {[%clk 0:03:14.9]} 13. Bxc4 {[%clk 0:03:28.3]} 13... Qa5 {[%clk 0:02:51.5]} 14. O-O {[%clk 0:03:21.9]} 14... Rfb8 {[%clk 0:02:49.4]} 15. a3 {[%clk 0:03:05.3]} 15... Rb7 {[%clk 0:02:37.2]} 16. Rfb1 {[%clk 0:02:37.7]} 16... Rab8 {[%clk 0:02:27.6]} 17. b4 {[%clk 0:02:23.8]} 17... cxb4 {[%clk 0:02:23.5]} 18. axb4 {[%clk 0:02:23.2]} 18... Qc7 {[%clk 0:02:22.7]} 19. Bxa6 {[%clk 0:02:07.1]} 19... Rxb4 {[%clk 0:02:21.7]} 20. Rxb4 {[%clk 0:01:55]} 20... Rxb4 {[%clk 0:02:21.6]} 21. Bd3 {[%clk 0:01:50.6]} 21... Rb8 {[%clk 0:01:54.4]} 22. Ra7 {[%clk 0:01:47.9]} 22... Qc8 {[%clk 0:01:53.6]} 23. Ba6 {[%clk 0:01:43.4]} 23... Qd8 {[%clk 0:01:51.1]} 24. Nb5 {[%clk 0:01:40.5]} 24... Nc5 {[%clk 0:01:44.3]} 25. Bxc5 {[%clk 0:01:17.2]} 25... dxc5 {[%clk 0:01:44.2]} 26. Qxc5 {[%clk 0:01:16.9]} 26... Nxe4 {[%clk 0:01:42.8]} 27. Qxe7 {[%clk 0:01:12.5]} 27... Qxd5 {[%clk 0:01:19.1]} 28. Bb7 {[%clk 0:00:58.8]} 28... Qd1+ {[%clk 0:00:55]} 29. Kh2 {[%clk 0:00:58.3]} 29... Nd2 {[%clk 0:00:54.5]} 30. Ra8 {[%clk 0:00:31.7]} 30... Nf1+ {[%clk 0:00:51.7]} 31. Kg1 {[%clk 0:00:29.1]} 31... Nd2+ {[%clk 0:00:51.6]} 32. Kh2 {[%clk 0:00:28.3]} 32... Rxa8 {[%clk 0:00:51.3]} 33. Bxa8 {[%clk 0:00:27.2]} 33... Nf1+ {[%clk 0:00:50.9]} 34. Kg1 {[%clk 0:00:25.9]} 34... Nd2+ {[%clk 0:00:50.8]} 35. Kh2 {[%clk 0:00:25.3]} 35... Bf8 {[%clk 0:00:50.7]} 36. Qe8 {[%clk 0:00:19.5]} 36... Nf1+ {[%clk 0:00:49.9]} 37. Kg1 {[%clk 0:00:18.9]} 37... Ne3+ {[%clk 0:00:41.5]} 38. Kh2 {[%clk 0:00:17.8]} 38... Nf5 {[%clk 0:00:41.4]} 39. Bf3 {[%clk 0:00:14.4]} 39... Qd2 {[%clk 0:00:38.3]} 40. Qe2 {[%clk 0:00:12.5]} 40... Qb4 {[%clk 0:00:35.9]} 41. g3 {[%clk 0:00:11.8]} 41... h5 {[%clk 0:00:34.4]} 42. Kg2 {[%clk 0:00:11.3]} 42... h4 {[%clk 0:00:33.3]} 43. g4 {[%clk 0:00:10.9]} 43... Ng7 {[%clk 0:00:33]} 44. Bd5 {[%clk 0:00:09.9]} 44... Qc5 {[%clk 0:00:32.1]} 45. Qc4 {[%clk 0:00:09]} 45... Qe7 {[%clk 0:00:31.2]} 46. Nd4 {[%clk 0:00:06.8]} 46... Ne8 {[%clk 0:00:30]} 47. Nf3 {[%clk 0:00:06.2]} 47... Nf6 {[%clk 0:00:28.4]} 48. Ng5 {[%clk 0:00:04.5]} 48... Qe5 {[%clk 0:00:26.7]} 49. Bxf7+ {[%clk 0:00:03.6]} 49... Kg7 {[%clk 0:00:26.4]} 50. Ne6+ {[%clk 0:00:02.4]} 50... Kxf7 {[%clk 0:00:24.7]} 51. Ng5+ {[%clk 0:00:01.3]} 51... Ke7 {[%clk 0:00:24]} 52. Qf7+ {[%clk 0:00:00.9]} 52... Kd6 {[%clk 0:00:23.6]} 53. Qxf8+ {[%clk 0:00:00.3]} 53... Kc6 {[%clk 0:00:23.3]} 0-1',
 '']

no need for png data all is already available in the json data, but it is interesting to see how the pgn data is structured and what information it contains.

In [33]:
len(group_data["players"])

404

In [34]:
group_data['games'].__len__()

202

# Feature Creation Part I

In [35]:
from urllib.error import HTTPError

rows = []
for tournament_index, tournament_url in enumerate(tournaments, start=1):
    request = Request(tournament_url, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=30) as response:
        tournament_data = json.load(response)
        tournament_name = tournament_data["name"]
        tournament_time = tournament_data["settings"]["time_control"]
        tournament_date_start = pd.to_datetime(tournament_data["start_time"], unit="s", utc=True)
        tournament_date_end = pd.to_datetime(tournament_data["finish_time"], unit="s", utc=True)

    for round_index, round_url in enumerate(tournament_data["rounds"], start=1):
        round_request = Request(round_url, headers={"User-Agent": USER_AGENT})
        try:
            with urlopen(round_request, timeout=30) as round_response:
                round_data = json.load(round_response)
        except HTTPError as error:
            print(f"Error at: round URL {round_url}, tournament={tournament_name}, round={round_index}, with error => {error}")
            continue

        for group_index, group_url in enumerate(round_data.get("groups", []), start=1):
            group_request = Request(group_url, headers={"User-Agent": USER_AGENT})
            try:
                with urlopen(group_request, timeout=30) as group_response:
                    group_data = json.load(group_response)
            except HTTPError as error:
                print(f"Error at: group URL {group_url}, tournament={tournament_name}, round={round_index}, group={group_index}, with error => {error}")
                continue

            for game_index, game in enumerate(group_data.get("games", []), start=1):
                white_player = game["white"]
                black_player = game["black"]

                white_rating = white_player["rating"]
                black_rating = black_player["rating"]

                try:
                    white_uuid = white_player["uuid"]
                    black_uuid = black_player["uuid"]
                except KeyError as error:
                    print(
                        f"Error at: game URL {game.get('url', '<unknown>')}, tournament={tournament_name}, "
                        f"round={round_index}, group={group_index}, game={game_index}, with error => {error}. "
                    )
                    continue

                row = {
                    "tournament_name": tournament_name,
                    "tournament_index": tournament_index,
                    "tournament_time": tournament_time,
                    "tournament_date_start": tournament_date_start,
                    "tournament_date_end": tournament_date_end,
                    "group_index": group_index,
                    "round_index": round_index,
                    "game_index": game_index,
                    "game_end_time": pd.to_datetime(game["end_time"], unit="s", utc=True),
                    "game_is_rated": game["rated"],
                    "game_time_control": game["time_control"],
                    "game_opening": game.get("eco"),
                    "white_player": white_player["username"].lower(),
                    "white_rating": white_rating,
                    "white_result": white_player["result"],
                    "white_uuid": white_uuid,
                    "black_player": black_player["username"].lower(),
                    "black_rating": black_rating,
                    "black_result": black_player["result"],
                    "black_uuid": black_uuid,
                    "rating_diff": white_rating - black_rating,
                    "rating_diff_sq": (white_rating - black_rating) ** 2,
                    "rating_diff_abs": abs(white_rating - black_rating),
                    "rating_ratio": white_rating / black_rating if black_rating != 0 else 1.0,
                    "rating_mean": (white_rating + black_rating) / 2.0,
                    "white_is_higher_rated": white_rating > black_rating,
                }

                rows.append(row)

df = pd.DataFrame(rows)
df.to_csv("titled_tuesday_games_fromnotebook.csv", index=False)

In [36]:
# Could we use the valid title abbreviations? (Valid title abbreviations are: GM, WGM, IM, WIM, FM, WFM, NM, WNM, CM, WCM.)
pd.concat([df[df.white_player.str.lower().str.contains("gm_|wgm_|im_|wim_|fm_|wfm_|nm_|wnm_|cm_|wcm_")]["white_player"].drop_duplicates(),
           df[df.black_player.str.lower().str.contains("gm_|wgm_|im_|wim_|fm_|wfm_|nm_|wnm_|cm_|wcm_")]["black_player"].drop_duplicates()])

175     im_alex_ivanov
228         gm_dmitrij
289            gm_path
380       ramu_k_fm_ft
2573    gm_huschenbeth
30          gm_dmitrij
102            gm_path
167       ramu_k_fm_ft
539     im_alex_ivanov
2184    gm_huschenbeth
dtype: object

Not worth it, not so many title abbreviations (we could search them in the profile but the work goes beyond scope due to data lekeage since the title could be post tournament and we will need to filter that information)

# Feature Creation Part II

In [37]:
df = pd.read_csv("titled_tuesday_games_fromnotebook.csv")

In [38]:
df.head()

,tournament_name,tournament_index,tournament_time,tournament_date_start,tournament_date_end,group_index,round_index,game_index,game_end_time,game_is_rated,game_time_control,game_opening,white_player,white_rating,white_result,white_uuid,black_player,black_rating,black_result,black_uuid,rating_diff,rating_diff_sq,rating_diff_abs,rating_ratio,rating_mean,white_is_higher_rated
0,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,1,2026-02-10 16:09:53+00:00,True,300,https://www.chess.com/openings/Modern-Defense-...,umuterdemgunduz,2682,timeout,0016479a-a347-11e9-b619-7d5b9e8b8800,hikaru,3316,win,6f4deb88-7718-11e3-8016-000000000000,-634,401956,634,0.808806,2999.0,False
1,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,2,2026-02-10 16:06:37+00:00,True,300,https://www.chess.com/openings/Sicilian-Defens...,lachesisq,3279,win,ea103016-2647-11e6-8040-000000000000,gorindeshi,2678,resigned,af27c69c-36ef-11ee-afee-879979d51b45,601,361201,601,1.224421,2978.5,True
2,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,3,2026-02-10 16:06:42+00:00,True,300,https://www.chess.com/openings/English-Opening...,jaisankars,2677,checkmated,cb754d68-e4f6-11ef-a68a-9be73e69b3c8,nikotheodorou,3252,win,4d8a88c8-4b2b-11eb-89ec-1b7cb3f4e61a,-575,330625,575,0.823186,2964.5,False
3,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,4,2026-02-10 16:08:09+00:00,True,300,https://www.chess.com/openings/Nimzowitsch-Lar...,gmwso,3230,resigned,50758188-90e9-11e6-8018-000000000000,gcamachomartinez,2691,win,fdec591c-c7f8-11e7-802e-000000000000,539,290521,539,1.200297,2960.5,True
4,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,5,2026-02-10 16:09:13+00:00,True,300,https://www.chess.com/openings/Indian-Game-Eas...,dey2580,2675,resigned,750ce062-0d0d-11e8-8014-000000000000,ghandeevam2003,3233,win,634b94f8-a0dd-11e4-8014-000000000000,-558,311364,558,0.827405,2954.0,False

In [39]:
df.shape

(4063, 26)

In [40]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
tournament_index,4063.0,1.501600,0.500059,1.000000,1.000000,2.000000,2.000000,2.000000e+00
tournament_time,4063.0,300.000000,0.000000,300.000000,300.000000,300.000000,300.000000,3.000000e+02
group_index,4063.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00
round_index,4063.0,5.606941,3.092744,1.000000,3.000000,5.000000,8.000000,1.100000e+01
game_index,4063.0,94.415949,55.865076,1.000000,47.000000,93.000000,139.000000,2.180000e+02
game_time_control,4063.0,300.000000,0.000000,300.000000,300.000000,300.000000,300.000000,3.000000e+02
white_rating,4063.0,2691.012552,276.450244,1608.000000,2500.000000,2673.000000,2890.000000,3.361000e+03
black_rating,4063.0,2689.225203,276.344663,1604.000000,2498.500000,2672.000000,2886.000000,3.365000e+03
rating_diff,4063.0,1.787349,273.782874,-1069.000000,-215.000000,39.000000,217.000000,1.265000e+03
rating_diff_sq,4063.0,74941.808024,88464.072434,0.000000,27556.000000,46656.000000,91204.000000,1.600225e+06
rating_diff_abs,4063.0,245.154319,121.839326,0.000000,166.000000,216.000000,302.000000,1.265000e+03
rating_ratio,4063.0,1.006110,0.105063,0.601268,0.922605,1.014804,1.082937,1.784739e+00
rating_mean,4063.0,2690.118878,240.117242,1937.500000,2519.250000,2676.500000,2860.000000,3.334500e+03

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4063 entries, 0 to 4062
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   tournament_name        4063 non-null   object
 1   tournament_index       4063 non-null   int64
 2   tournament_time        4063 non-null   int64
 3   tournament_date_start  4063 non-null   object
 4   tournament_date_end    4063 non-null   object
 5   group_index            4063 non-null   int64
 6   round_index            4063 non-null   int64
 7   game_index             4063 non-null   int64
 8   game_end_time          4063 non-null   object
 9   game_is_rated          4063 non-null   bool
 10  game_time_control      4063 non-null   int64
 11  game_opening           4063 non-null   object
 12  white_player           4063 non-null   object
 13  white_rating           4063 non-null   int64
 14  white_result           4063 non-null   object
 15  white_uuid             4063 non-null   object
 16  black_player           4063 non-null   object
 17  black_rating           4063 non-null   int64
 18  black_result           4063 non-null   object
 19  black_uuid             4063 non-null   object
 20  rating_diff            4063 non-null   int64
 21  rating_diff_sq         4063 non-null   int64
 22  rating_diff_abs        4063 non-null   int64
 23  rating_ratio           4063 non-null   float64
 24  rating_mean            4063 non-null   float64
 25  white_is_higher_rated  4063 non-null   bool
dtypes: bool(2), float64(2), int64(11), object(11)
memory usage: 769.9+ KB

no null values!!!!

In [42]:
# duplicate games
print("duplicated games= ",df.duplicated(subset=["white_uuid", "black_uuid", "tournament_name", "tournament_time", "tournament_date_start",  "group_index", "round_index", "game_index"]).sum())

duplicated games=  0

In [43]:
df.groupby(["white_result", "black_result"]).size()

white_result        black_result
50move              50move                   4
agreed              agreed                  18
checkmated          win                    353
insufficient        insufficient            58
repetition          repetition             168
resigned            win                    981
stalemate           stalemate               22
timeout             win                    463
timevsinsufficient  timevsinsufficient      45
win                 checkmated             387
                    resigned              1097
                    timeout                467
dtype: int64

In [44]:
df.game_is_rated.unique()

array([ True])

In [45]:
df.white_player.apply(lambda x: x.split("_")[0]).value_counts()

white_player
gm               22
robert           17
m                14
taglit           12
szparu           12
                 ..
jup1978           1
wanyaland         1
garfield000       1
lion-al-messi     1
egehany09         1
Name: count, Length: 682, dtype: int64

As expected the data is super clean.

In [46]:
#from documentation
LOSS_RESULTS = [
    "timeout","resigned","checkmated",
]

DRAW_RESULTS = [
	"agreed",
	"50move",
	"insufficient",
	"repetition",
	"stalemate",
	"timevsinsufficient",
]

# Row Functions
def game_outcome(row: dict) -> str:
    white_result = row.white_result  
    if white_result in LOSS_RESULTS:
        return "loss"
    if white_result in DRAW_RESULTS:
        return "draw"
    return "win"

def white_points_from_outcome(outcome: str) -> float:
	if outcome == "win":
		return 1.0
	if outcome == "draw":
		return 0.5
	return 0.0

In [47]:
# This block has mostly been done with AI , base on a feature engineering prompt and some examples of code I have started (basically iterating with the IA to keep the code readable and minimalistic).

ORDER_COLS = [
    "tournament_index",
    "round_index",
    "group_index",
    "game_index",
    "game_end_time",
]

HISTORY_GROUP_COLS = ["tournament_index", "player_uuid"]
SCOPE_FLAG_COLS = {
    "as_white": "_is_white",
    "as_black": "_is_black",
    "as_any": "_is_any",
}

# this is the basic block
# for building player appearances and adding history features,
# it is designed to allow for different scopes
def _build_player_appearances(df):
    out = df.sort_values(ORDER_COLS).copy()
    out["_row_id"] = out.index

    base_cols = ORDER_COLS + ["_row_id"]

    white = out[base_cols + ["white_uuid", "white_outcome", "white_points"]].copy()
    white.columns = base_cols + ["player_uuid", "outcome", "points"]
    white["row_prefix"] = "white"
    white["appearance_side"] = "white"

    black = out[base_cols + ["black_uuid", "black_outcome", "black_points"]].copy()
    black.columns = base_cols + ["player_uuid", "outcome", "points"]
    black["row_prefix"] = "black"
    black["appearance_side"] = "black"

    appearances = pd.concat([white, black], ignore_index=True)
    appearances = appearances.sort_values(ORDER_COLS + ["_row_id", "row_prefix"]).reset_index(drop=True)

    appearances["_is_white"] = (appearances["appearance_side"] == "white").astype(int)
    appearances["_is_black"] = (appearances["appearance_side"] == "black").astype(int)
    appearances["_is_any"] = 1

    appearances["_is_win"] = (appearances["outcome"] == "win").astype(int)
    appearances["_is_draw"] = (appearances["outcome"] == "draw").astype(int)
    appearances["_is_loss"] = (appearances["outcome"] == "loss").astype(int)

    return out, appearances

# this function adds cumulative history features
# for a given scope (white, black, or any)
def _add_scope_history_features(appearances, scope_label):
    scope_flag_col = SCOPE_FLAG_COLS[scope_label]
    grouped = appearances.groupby(HISTORY_GROUP_COLS, sort=False)

    appearances[f"_points_{scope_label}"] = appearances["points"] * appearances[scope_flag_col]
    appearances[f"_wins_{scope_label}"] = appearances["_is_win"] * appearances[scope_flag_col]
    appearances[f"_draws_{scope_label}"] = appearances["_is_draw"] * appearances[scope_flag_col]
    appearances[f"_losses_{scope_label}"] = appearances["_is_loss"] * appearances[scope_flag_col]

    previous_games_col = f"previous_games_{scope_label}"
    appearances[previous_games_col] = (
        grouped[scope_flag_col].cumsum() - appearances[scope_flag_col]
    ).astype(int)

    appearances[f"previous_points_{scope_label}"] = (
        grouped[f"_points_{scope_label}"].cumsum() - appearances[f"_points_{scope_label}"]
    )

    previous_wins = (
        grouped[f"_wins_{scope_label}"].cumsum() - appearances[f"_wins_{scope_label}"]
    ).astype(int)

    appearances[f"previous_draws_{scope_label}"] = (
        grouped[f"_draws_{scope_label}"].cumsum() - appearances[f"_draws_{scope_label}"]
    ).astype(int)

    appearances[f"previous_losses_{scope_label}"] = (
        grouped[f"_losses_{scope_label}"].cumsum() - appearances[f"_losses_{scope_label}"]
    ).astype(int)

    previous_games = appearances[previous_games_col].where(
        appearances[previous_games_col] > 0
    )

    appearances[f"previous_win_pct_{scope_label}"] = (
        previous_wins.div(previous_games).fillna(0.0) * 100.0
    )

    appearances[f"previous_draw_pct_{scope_label}"] = (
        appearances[f"previous_draws_{scope_label}"].div(previous_games).fillna(0.0) * 100.0
    )

    appearances[f"previous_loss_pct_{scope_label}"] = (
        appearances[f"previous_losses_{scope_label}"].div(previous_games).fillna(0.0) * 100.0
    )

    return appearances

# this is the main function to call to 
# add player history features to the original dataframe,
def add_player_history_features(df, scopes=("as_white", "as_black", "as_any")):
    out, appearances = _build_player_appearances(df)
    feature_cols = []

    for scope_label in scopes:
        appearances = _add_scope_history_features(appearances, scope_label)
        scoped_feature_cols = [
            f"previous_points_{scope_label}",
            f"previous_draws_{scope_label}",
            f"previous_losses_{scope_label}",
            f"previous_win_pct_{scope_label}",
            f"previous_draw_pct_{scope_label}",
            f"previous_loss_pct_{scope_label}",
        ]
        if scope_label != "as_any":
            scoped_feature_cols.insert(0, f"previous_games_{scope_label}")
        feature_cols.extend(scoped_feature_cols)

    for row_prefix in ("white", "black"):
        row_features = appearances[appearances["row_prefix"] == row_prefix].set_index("_row_id")

        for feature_col in feature_cols:
            new_col = f"{row_prefix}_{feature_col}"
            values = row_features[feature_col].reindex(out.index).fillna(0)

            if feature_col.startswith("previous_points_") or "_pct_" in feature_col:
                out[new_col] = values.astype(float)
            else:
                out[new_col] = values.astype(int)

    return out.drop(columns=["_row_id"]).sort_index()

In [48]:
# No AI anymore
df['white_outcome'] = df.apply(game_outcome, axis=1)
df['black_outcome'] = df['white_outcome'].map({'win': 'loss', 'loss': 'win', 'draw': 'draw'})
df['white_points'] = df['white_outcome'].apply(white_points_from_outcome)
df['black_points'] = df['black_outcome'].apply(white_points_from_outcome)

df = add_player_history_features(df) #<-- function from AI

In [49]:
df.head(3)

,tournament_name,tournament_index,tournament_time,tournament_date_start,tournament_date_end,group_index,round_index,game_index,game_end_time,game_is_rated,game_time_control,game_opening,white_player,white_rating,white_result,white_uuid,black_player,black_rating,black_result,black_uuid,rating_diff,rating_diff_sq,rating_diff_abs,rating_ratio,rating_mean,white_is_higher_rated,white_outcome,black_outcome,white_points,black_points,white_previous_games_as_white,white_previous_points_as_white,white_previous_draws_as_white,white_previous_losses_as_white,white_previous_win_pct_as_white,white_previous_draw_pct_as_white,white_previous_loss_pct_as_white,white_previous_games_as_black,white_previous_points_as_black,white_previous_draws_as_black,white_previous_losses_as_black,white_previous_win_pct_as_black,white_previous_draw_pct_as_black,white_previous_loss_pct_as_black,white_previous_points_as_any,white_previous_draws_as_any,white_previous_losses_as_any,white_previous_win_pct_as_any,white_previous_draw_pct_as_any,white_previous_loss_pct_as_any,black_previous_games_as_white,black_previous_points_as_white,black_previous_draws_as_white,black_previous_losses_as_white,black_previous_win_pct_as_white,black_previous_draw_pct_as_white,black_previous_loss_pct_as_white,black_previous_games_as_black,black_previous_points_as_black,black_previous_draws_as_black,black_previous_losses_as_black,black_previous_win_pct_as_black,black_previous_draw_pct_as_black,black_previous_loss_pct_as_black,black_previous_points_as_any,black_previous_draws_as_any,black_previous_losses_as_any,black_previous_win_pct_as_any,black_previous_draw_pct_as_any,black_previous_loss_pct_as_any
0,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,1,2026-02-10 16:09:53+00:00,True,300,https://www.chess.com/openings/Modern-Defense-...,umuterdemgunduz,2682,timeout,0016479a-a347-11e9-b619-7d5b9e8b8800,hikaru,3316,win,6f4deb88-7718-11e3-8016-000000000000,-634,401956,634,0.808806,2999.0,False,loss,win,0.0,1.0,0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0
1,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,2,2026-02-10 16:06:37+00:00,True,300,https://www.chess.com/openings/Sicilian-Defens...,lachesisq,3279,win,ea103016-2647-11e6-8040-000000000000,gorindeshi,2678,resigned,af27c69c-36ef-11ee-afee-879979d51b45,601,361201,601,1.224421,2978.5,True,win,loss,1.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0
2,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,3,2026-02-10 16:06:42+00:00,True,300,https://www.chess.com/openings/English-Opening...,jaisankars,2677,checkmated,cb754d68-e4f6-11ef-a68a-9be73e69b3c8,nikotheodorou,3252,win,4d8a88c8-4b2b-11eb-89ec-1b7cb3f4e61a,-575,330625,575,0.823186,2964.5,False,loss,win,0.0,1.0,0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0

In [52]:
cols = ['tournament_name', 'tournament_index', 'tournament_time',
       'tournament_date_start', 'tournament_date_end', 'group_index',
       'round_index', 'game_index', 'game_end_time', 'game_is_rated',
       'game_time_control', 'game_opening', 'white_player', 'white_rating',
       'white_result', 'white_uuid', 'black_player', 'black_rating',
        'rating_diff', 'rating_diff_sq',
       'rating_diff_abs', 'rating_ratio', 'rating_mean',
       'white_is_higher_rated', 'white_outcome', 'black_outcome',
       'white_points', 'black_points', 'white_previous_games_as_white',
       'white_previous_points_as_white', 'white_previous_draws_as_white',
       'white_previous_losses_as_white', 'white_previous_win_pct_as_white',
       'white_previous_draw_pct_as_white', 'white_previous_loss_pct_as_white',
       'white_previous_games_as_black', 'white_previous_points_as_black',
       'white_previous_draws_as_black', 'white_previous_losses_as_black',
       'white_previous_win_pct_as_black', 'white_previous_draw_pct_as_black',
       'white_previous_loss_pct_as_black', 'white_previous_points_as_any',
       'white_previous_draws_as_any', 'white_previous_losses_as_any',
       'white_previous_win_pct_as_any', 'white_previous_draw_pct_as_any',
       'white_previous_loss_pct_as_any', 'black_previous_games_as_white',
       ]

In [53]:
# Testing some queries

m1 = df.white_player == 'klimkoj'
m2 = False
m2 = df.black_player == 'klimkoj'
m3 = True
m3 = df.tournament_index == 1
df[(m1 | m2) & m3][cols].sort_values(["tournament_index", 'group_index', 'round_index', 'game_index'])

,tournament_name,tournament_index,tournament_time,tournament_date_start,tournament_date_end,group_index,round_index,game_index,game_end_time,game_is_rated,game_time_control,game_opening,white_player,white_rating,white_result,white_uuid,black_player,black_rating,rating_diff,rating_diff_sq,rating_diff_abs,rating_ratio,rating_mean,white_is_higher_rated,white_outcome,black_outcome,white_points,black_points,white_previous_games_as_white,white_previous_points_as_white,white_previous_draws_as_white,white_previous_losses_as_white,white_previous_win_pct_as_white,white_previous_draw_pct_as_white,white_previous_loss_pct_as_white,white_previous_games_as_black,white_previous_points_as_black,white_previous_draws_as_black,white_previous_losses_as_black,white_previous_win_pct_as_black,white_previous_draw_pct_as_black,white_previous_loss_pct_as_black,white_previous_points_as_any,white_previous_draws_as_any,white_previous_losses_as_any,white_previous_win_pct_as_any,white_previous_draw_pct_as_any,white_previous_loss_pct_as_any,black_previous_games_as_white
81,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,82,2026-02-10 16:09:25+00:00,True,300,https://www.chess.com/openings/Modern-Defense-...,klimkoj,2944,win,aa2e4780-b072-11e5-8002-000000000000,safikiet,2547,397,157609,397,1.155870,2745.5,True,win,loss,1.0,0.0,0,0.0,0,0,0.000000,0.000000,0.0,0,0.0,0,0,0.000000,0.0,0.000000,0.0,0,0,0.000000,0.000000,0.000000,0
271,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,2,70,2026-02-10 16:19:56+00:00,True,300,https://www.chess.com/openings/Nimzowitsch-Lar...,semetey,2687,resigned,a5d3e61a-bc42-11df-8004-000000000000,klimkoj,2947,-260,67600,260,0.911775,2817.0,False,loss,win,0.0,1.0,0,0.0,0,0,0.000000,0.000000,0.0,1,1.0,0,0,100.000000,0.0,0.000000,1.0,0,0,100.000000,0.000000,0.000000,1
432,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,3,18,2026-02-10 16:33:15+00:00,True,300,https://www.chess.com/openings/Ruy-Lopez-Openi...,klimkoj,2952,timevsinsufficient,aa2e4780-b072-11e5-8002-000000000000,javokhir_sindarov05,3169,-217,47089,217,0.931524,3060.5,False,draw,draw,0.5,0.5,1,1.0,0,0,100.000000,0.000000,0.0,1,1.0,0,0,100.000000,0.0,0.000000,2.0,0,0,100.000000,0.000000,0.000000,1
648,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,4,23,2026-02-10 16:40:31+00:00,True,300,https://www.chess.com/openings/Sicilian-Defens...,klimkoj,2964,win,aa2e4780-b072-11e5-8002-000000000000,grischuk,3147,-183,33489,183,0.941849,3055.5,False,win,loss,1.0,0.0,2,1.5,1,0,50.000000,50.000000,0.0,1,1.0,0,0,100.000000,0.0,0.000000,2.5,1,0,66.666667,33.333333,0.000000,2
841,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,5,13,2026-02-10 16:57:32+00:00,True,300,https://www.chess.com/openings/Kings-Pawn-Open...,fabianocaruana,3163,win,5ebdca54-8f15-11e2-800a-000000000000,klimkoj,2960,203,41209,203,1.068581,3061.5,True,win,loss,1.0,0.0,2,2.0,0,0,100.000000,0.000000,0.0,2,1.5,1,0,50.000000,50.0,0.000000,3.5,1,0,75.000000,25.000000,0.000000,3
1064,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,6,41,2026-02-10 17:08:49+00:00,True,300,https://www.chess.com/openings/Nimzo-Indian-De...,kildepiotr,2820,resigned,336d7186-46bf-11e7-8022-000000000000,klimkoj,2965,-145,21025,145,0.951096,2892.5,False,loss,win,0.0,1.0,2,0.5,1,1,0.000000,50.000000,50.0,3,3.0,0,0,100.000000,0.0,0.000000,3.5,1,1,60.000000,20.000000,20.000000,3
1236,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,7,21,2026-02-10 17:20:08+00:00,True,300,https://www.chess.com/openings/Sicilian-Defens...,klimkoj,2961,resigned,aa2e4780-b072-11e5-8002-000000000000,chessfighter_2011,3163,-202,40804,202,0.936137,3062.0,False,loss,win,0.0,1.0,3,2.5,1,0,66.666667,33.333333,0.0,3,2.0,0,1,66.666667,0.0,33.333333,4.5,1,1,66.666667,16.666667,16.666667,3
1442,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,8,44,2026-02-10 17:32:46+00:00,True,300,https://www.chess.com/openings/Queens-Gambit-D...,manitodeplomo,2785,resigned,4a94108c-2672-11e0-8026-000000000000,klimkoj,2965,-180,32400,180,0.939292,2875.0,False,loss,win,0.0,1.0,4,2.5,1,1,50.000000,25.000000,25.0,3,2.0,0,1,66.666667,0.0,33.333333,4.5,1,2,57.142857,14.285714,28.571429,4
1605,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,9,32,2026-02-10 17:52:05+00:00,True,300,https://www.chess.com/openings/Four-Knights-Ga...,vovachesss,2863,timeout,2f89a152-727d-11e4-804c-000000000000,klimkoj,2971,-108,11664,108,0.963649,2917.0,False,loss,win,0.0,1.0,4,2.5,1,1,50.000000,25.000000,25.0,4,3.0,0,1,75.000000,0.0,25.000000,5.5,1,2,62.500000,12.500000,25.000000,4
1751,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,10,20,2026-02-10 18:02:25+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,klimkoj,2969,resigned,aa2e4780-b072-11e5-8002-000000000000,hikaru,3292,-323,104329,323,0.901883,3130.5,False,loss,win,0.0,1.0,4,2.5,1,1,50.000000,25.000000,25.0,5,4.0,0,1,80.000000,0.0,20.000000,6.5,1,2,66.666667,11.111111,22.222222,4

In [54]:
# Testing some queries

m1 = df.white_player == 'fabianocaruana'
m2 = df.black_player == 'fabianocaruana'
m3 = df.tournament_index == 1
df[(m1 | m2) & m3][cols].sort_values(["tournament_index", 'group_index', 'round_index', 'game_index'])

,tournament_name,tournament_index,tournament_time,tournament_date_start,tournament_date_end,group_index,round_index,game_index,game_end_time,game_is_rated,game_time_control,game_opening,white_player,white_rating,white_result,white_uuid,black_player,black_rating,rating_diff,rating_diff_sq,rating_diff_abs,rating_ratio,rating_mean,white_is_higher_rated,white_outcome,black_outcome,white_points,black_points,white_previous_games_as_white,white_previous_points_as_white,white_previous_draws_as_white,white_previous_losses_as_white,white_previous_win_pct_as_white,white_previous_draw_pct_as_white,white_previous_loss_pct_as_white,white_previous_games_as_black,white_previous_points_as_black,white_previous_draws_as_black,white_previous_losses_as_black,white_previous_win_pct_as_black,white_previous_draw_pct_as_black,white_previous_loss_pct_as_black,white_previous_points_as_any,white_previous_draws_as_any,white_previous_losses_as_any,white_previous_win_pct_as_any,white_previous_draw_pct_as_any,white_previous_loss_pct_as_any,black_previous_games_as_white
27,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,28,2026-02-10 16:10:12+00:00,True,300,https://www.chess.com/openings/Kings-Pawn-Open...,fabianocaruana,3156,win,5ebdca54-8f15-11e2-800a-000000000000,earlybird2012,2641,515,265225,515,1.195002,2898.5,True,win,loss,1.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0,0.000000,0.000000,0.000000,0.0,0,0,0.000000,0.000000,0.000000,0
225,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,2,24,2026-02-10 16:18:22+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,viktorskliarov,2801,resigned,cd041d14-50d9-11e5-8038-000000000000,fabianocaruana,3158,-357,127449,357,0.886954,2979.5,False,loss,win,0.0,1.0,0,0.0,0,0,0.0,0.0,0.0,1,1.0,0,0,100.000000,0.000000,0.000000,1.0,0,0,100.000000,0.000000,0.000000,1
434,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,3,20,2026-02-10 16:31:15+00:00,True,300,https://www.chess.com/openings/Kings-Pawn-Open...,fabianocaruana,3162,win,5ebdca54-8f15-11e2-800a-000000000000,qminhlcf,2939,223,49729,223,1.075876,3050.5,True,win,loss,1.0,0.0,1,1.0,0,0,100.0,0.0,0.0,1,1.0,0,0,100.000000,0.000000,0.000000,2.0,0,0,100.000000,0.000000,0.000000,1
638,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,4,13,2026-02-10 16:42:41+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,iball95,3006,repetition,b0a717d0-601f-11e4-801c-000000000000,fabianocaruana,3159,-153,23409,153,0.951567,3082.5,False,draw,draw,0.5,0.5,2,2.0,0,0,100.0,0.0,0.0,1,1.0,0,0,100.000000,0.000000,0.000000,3.0,0,0,100.000000,0.000000,0.000000,2
841,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,5,13,2026-02-10 16:57:32+00:00,True,300,https://www.chess.com/openings/Kings-Pawn-Open...,fabianocaruana,3163,win,5ebdca54-8f15-11e2-800a-000000000000,klimkoj,2960,203,41209,203,1.068581,3061.5,True,win,loss,1.0,0.0,2,2.0,0,0,100.0,0.0,0.0,2,1.5,1,0,50.000000,50.000000,0.000000,3.5,1,0,75.000000,25.000000,0.000000,3
1027,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,6,4,2026-02-10 17:12:35+00:00,True,300,https://www.chess.com/openings/English-Opening...,sibelephant,3237,win,8961cafa-071e-11e7-803c-000000000000,fabianocaruana,3157,80,6400,80,1.025341,3197.0,True,win,loss,1.0,0.0,2,2.0,0,0,100.0,0.0,0.0,3,2.5,1,0,66.666667,33.333333,0.000000,4.5,1,0,80.000000,20.000000,0.000000,3
1237,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,7,22,2026-02-10 17:22:52+00:00,True,300,https://www.chess.com/openings/Kings-Indian-De...,fabianocaruana,3162,win,5ebdca54-8f15-11e2-800a-000000000000,jcibarra,3015,147,21609,147,1.048756,3088.5,True,win,loss,1.0,0.0,3,3.0,0,0,100.0,0.0,0.0,3,1.5,1,1,33.333333,33.333333,33.333333,4.5,1,1,66.666667,16.666667,16.666667,3
1413,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,8,15,2026-02-10 17:35:26+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,nitzan_steinberg,2958,timeout,b2d28062-2742-11e6-8022-000000000000,fabianocaruana,3166,-208,43264,208,0.934302,3062.0,False,loss,win,0.0,1.0,4,2.5,1,1,50.0,25.0,25.0,3,3.0,0,0,100.000000,0.000000,0.000000,5.5,1,1,71.428571,14.285714,14.285714,4
1580,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,9,7,2026-02-10 17:52:13+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,konavets,3230,win,ef1e2854-f97a-11e1-8022-000000000000,fabianocaruana,3159,71,5041,71,1.022475,3194.5,True,win,loss,1.0,0.0,4,3.5,1,0,75.0,25.0,0.0,4,3.0,0,1,75.000000,0.000000,25.000000,6.5,1,1,75.000000,12.500000,12.500000,4
1749,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,10,18,2026-02-10 18:01:55+00:00,True,300,https://www.chess.com/openings/Sicilian-Defens...,fabianocaruana,3163,win,5ebdca54-8f15-11e2-800a-000000000000,ckgchess,2969,194,37636,194,1.065342,3066.0,True,win,loss,1.0,0.0,4,4.0,0,0,100.0,0.0,0.0,5,2.5,1,2,40.000000,20.000000,40.000000,6.5,1,2,66.666667,11.111111,22.222222,5
1890,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,11,9,2026-02-10 18:15:06+00:00,True,300,https://www.chess.com/openings/Reti-Opening-Ki...,polish_fighter3000,3220,win,32b2e99a-7bb3-11e8-8042-000000000000,fabianocaruana,3156,64,4096,64,1.020279,3188.0,True,win,loss,1.0,0.0,5,4.5,1,0,80.0,20.0,0.0,5,3.0,2,1,40.000000,40.000000,20.000000,7.5,3,1,60.000000,30.000000,10.000000,5

In [55]:
# Testing some queries

m1 = df.white_player == 'fabianocaruana'
m2 = df.black_player == 'fabianocaruana'
 
df[(m1 | m2) ][cols].sort_values(["tournament_index", 'group_index', 'round_index', 'game_index'])

,tournament_name,tournament_index,tournament_time,tournament_date_start,tournament_date_end,group_index,round_index,game_index,game_end_time,game_is_rated,game_time_control,game_opening,white_player,white_rating,white_result,white_uuid,black_player,black_rating,rating_diff,rating_diff_sq,rating_diff_abs,rating_ratio,rating_mean,white_is_higher_rated,white_outcome,black_outcome,white_points,black_points,white_previous_games_as_white,white_previous_points_as_white,white_previous_draws_as_white,white_previous_losses_as_white,white_previous_win_pct_as_white,white_previous_draw_pct_as_white,white_previous_loss_pct_as_white,white_previous_games_as_black,white_previous_points_as_black,white_previous_draws_as_black,white_previous_losses_as_black,white_previous_win_pct_as_black,white_previous_draw_pct_as_black,white_previous_loss_pct_as_black,white_previous_points_as_any,white_previous_draws_as_any,white_previous_losses_as_any,white_previous_win_pct_as_any,white_previous_draw_pct_as_any,white_previous_loss_pct_as_any,black_previous_games_as_white
27,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,1,28,2026-02-10 16:10:12+00:00,True,300,https://www.chess.com/openings/Kings-Pawn-Open...,fabianocaruana,3156,win,5ebdca54-8f15-11e2-800a-000000000000,earlybird2012,2641,515,265225,515,1.195002,2898.5,True,win,loss,1.0,0.0,0,0.0,0,0,0.000000,0.0,0.000000,0,0.0,0,0,0.000000,0.000000,0.000000,0.0,0,0,0.000000,0.000000,0.000000,0
225,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,2,24,2026-02-10 16:18:22+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,viktorskliarov,2801,resigned,cd041d14-50d9-11e5-8038-000000000000,fabianocaruana,3158,-357,127449,357,0.886954,2979.5,False,loss,win,0.0,1.0,0,0.0,0,0,0.000000,0.0,0.000000,1,1.0,0,0,100.000000,0.000000,0.000000,1.0,0,0,100.000000,0.000000,0.000000,1
434,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,3,20,2026-02-10 16:31:15+00:00,True,300,https://www.chess.com/openings/Kings-Pawn-Open...,fabianocaruana,3162,win,5ebdca54-8f15-11e2-800a-000000000000,qminhlcf,2939,223,49729,223,1.075876,3050.5,True,win,loss,1.0,0.0,1,1.0,0,0,100.000000,0.0,0.000000,1,1.0,0,0,100.000000,0.000000,0.000000,2.0,0,0,100.000000,0.000000,0.000000,1
638,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,4,13,2026-02-10 16:42:41+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,iball95,3006,repetition,b0a717d0-601f-11e4-801c-000000000000,fabianocaruana,3159,-153,23409,153,0.951567,3082.5,False,draw,draw,0.5,0.5,2,2.0,0,0,100.000000,0.0,0.000000,1,1.0,0,0,100.000000,0.000000,0.000000,3.0,0,0,100.000000,0.000000,0.000000,2
841,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,5,13,2026-02-10 16:57:32+00:00,True,300,https://www.chess.com/openings/Kings-Pawn-Open...,fabianocaruana,3163,win,5ebdca54-8f15-11e2-800a-000000000000,klimkoj,2960,203,41209,203,1.068581,3061.5,True,win,loss,1.0,0.0,2,2.0,0,0,100.000000,0.0,0.000000,2,1.5,1,0,50.000000,50.000000,0.000000,3.5,1,0,75.000000,25.000000,0.000000,3
1027,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,6,4,2026-02-10 17:12:35+00:00,True,300,https://www.chess.com/openings/English-Opening...,sibelephant,3237,win,8961cafa-071e-11e7-803c-000000000000,fabianocaruana,3157,80,6400,80,1.025341,3197.0,True,win,loss,1.0,0.0,2,2.0,0,0,100.000000,0.0,0.000000,3,2.5,1,0,66.666667,33.333333,0.000000,4.5,1,0,80.000000,20.000000,0.000000,3
1237,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,7,22,2026-02-10 17:22:52+00:00,True,300,https://www.chess.com/openings/Kings-Indian-De...,fabianocaruana,3162,win,5ebdca54-8f15-11e2-800a-000000000000,jcibarra,3015,147,21609,147,1.048756,3088.5,True,win,loss,1.0,0.0,3,3.0,0,0,100.000000,0.0,0.000000,3,1.5,1,1,33.333333,33.333333,33.333333,4.5,1,1,66.666667,16.666667,16.666667,3
1413,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,8,15,2026-02-10 17:35:26+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,nitzan_steinberg,2958,timeout,b2d28062-2742-11e6-8022-000000000000,fabianocaruana,3166,-208,43264,208,0.934302,3062.0,False,loss,win,0.0,1.0,4,2.5,1,1,50.000000,25.0,25.000000,3,3.0,0,0,100.000000,0.000000,0.000000,5.5,1,1,71.428571,14.285714,14.285714,4
1580,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,9,7,2026-02-10 17:52:13+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,konavets,3230,win,ef1e2854-f97a-11e1-8022-000000000000,fabianocaruana,3159,71,5041,71,1.022475,3194.5,True,win,loss,1.0,0.0,4,3.5,1,0,75.000000,25.0,0.000000,4,3.0,0,1,75.000000,0.000000,25.000000,6.5,1,1,75.000000,12.500000,12.500000,4
1749,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,10,18,2026-02-10 18:01:55+00:00,True,300,https://www.chess.com/openings/Sicilian-Defens...,fabianocaruana,3163,win,5ebdca54-8f15-11e2-800a-000000000000,ckgchess,2969,194,37636,194,1.065342,3066.0,True,win,loss,1.0,0.0,4,4.0,0,0,100.000000,0.0,0.000000,5,2.5,1,2,40.000000,20.000000,40.000000,6.5,1,2,66.666667,11.111111,22.222222,5
1890,Titled-Tuesday-Blitz-February-10-2026,1,300,2026-02-10 16:00:00+00:00,2026-02-10 18:15:55+00:00,1,11,9,2026-02-10 18:15:06+00:00,True,300,https://www.chess.com/openings/Reti-Opening-Ki...,polish_fighter3000,3220,win,32b2e99a-7bb3-11e8-8042-000000000000,fabianocaruana,3156,64,4096,64,1.020279,3188.0,True,win,loss,1.0,0.0,5,4.5,1,0,80.000000,20.0,0.000000,5,3.0,2,1,40.000000,40.000000,20.000000,7.5,3,1,60.000000,30.000000,10.000000,5
2029,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,1,5,2026-03-10 16:06:01+00:00,True,300,https://www.chess.com/openings/Alapin-Sicilian...,fabianocaruana,3263,win,5ebdca54-8f15-11e2-800a-000000000000,kz_champ_gm,2660,603,363609,603,1.226692,2961.5,True,win,loss,1.0,0.0,0,0.0,0,0,0.000000,0.0,0.000000,0,0.0,0,0,0.000000,0.000000,0.000000,0.0,0,0,0.000000,0.000000,0.000000,0
2233,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,2,5,2026-03-10 16:18:58+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,chessqueen,2808,resigned,6e746188-6058-11e2-8040-000000000000,fabianocaruana,3264,-456,207936,456,0.860294,3036.0,False,loss,win,0.0,1.0,0,0.0,0,0,0.000000,0.0,0.000000,1,1.0,0,0,100.000000,0.000000,0.000000,1.0,0,0,100.000000,0.000000,0.000000,1
2451,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,3,5,2026-03-10 16:30:59+00:00,True,300,https://www.chess.com/openings/Sicilian-Defens...,fabianocaruana,3251,resigned,5ebdca54-8f15-11e2-800a-000000000000,ohanyaneminchess,2983,268,71824,268,1.089842,3117.0,True,loss,win,0.0,1.0,1,1.0,0,0,100.000000,0.0,0.000000,1,1.0,0,0,100.000000,0.000000,0.000000,2.0,0,0,100.000000,0.000000,0.000000,1
2690,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,4,30,2026-03-10 16:41:08+00:00,True,300,https://www.chess.com/openings/Caro-Kann-Defen...,logicbaba,2778,resigned,3aa55ff4-5b2d-11e7-8028-000000000000,fabianocaruana,3252,-474,224676,474,0.854244,3015.0,False,loss,win,0.0,1.0,1,0.0,0,1,0.000000,0.0,100.000000,2,2.0,0,0,100.000000,0.000000,0.000000,2.0,0,1,66.666667,0.000000,33.333333,2
2884,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,5,17,2026-03-10 17:00:49+00:00,True,300,https://www.chess.com/openings/Sicilian-Defens...,fabianocaruana,3254,win,5ebdca54-8f15-11e2-800a-000000000000,tacticthunder,2916,338,114244,338,1.115912,3085.0,True,win,loss,1.0,0.0,2,1.0,0,1,50.000000,0.0,50.000000,2,2.0,0,0,100.000000,0.000000,0.000000,3.0,0,1,75.000000,0.000000,25.000000,2
3075,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,6,11,2026-03-10 17:06:13+00:00,True,300,https://www.chess.com/openings/Nimzo-Indian-De...,gmkrikor,3019,resigned,34b06608-0857-11dd-8007-000000000000,fabianocaruana,3257,-238,56644,238,0.926927,3138.0,False,loss,win,0.0,1.0,2,2.0,0,0,100.000000,0.0,0.000000,3,2.0,0,1,66.666667,0.000000,33.333333,4.0,0,1,80.000000,0.000000,20.000000,3
3260,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,7,5,2026-03-10 17:20:43+00:00,True,300,https://www.chess.com/openings/Modern-Defense-...,fabianocaruana,3261,win,5ebdca54-8f15-11e2-800a-000000000000,moro182,3074,187,34969,187,1.060833,3167.5,True,win,loss,1.0,0.0,3,2.0,0,1,66.666667,0.0,33.333333,3,3.0,0,0,100.000000,0.000000,0.000000,5.0,0,1,83.333333,0.000000,16.666667,3
3442,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,8,4,2026-03-10 17:31:43+00:00,True,300,https://www.chess.com/openings/London-System-3...,wonderfultime,3128,win,ca45ce90-c60d-11e3-8004-000000000000,fabianocaruana,3250,-122,14884,122,0.962462,3189.0,False,win,loss,1.0,0.0,3,3.0,0,0,100.000000,0.0,0.000000,4,3.0,0,1,75.000000,0.000000,25.000000,6.0,0,1,85.714286,0.000000,14.285714,4
3619,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,9,9,2026-03-10 17:51:42+00:00,True,300,https://www.chess.com/openings/Queens-Gambit-D...,fabianocaruana,3255,win,5ebdca54-8f15-11e2-800a-000000000000,vaathi_coming,3089,166,27556,166,1.053739,3172.0,True,win,loss,1.0,0.0,4,3.0,0,1,75.000000,0.0,25.000000,4,3.0,0,1,75.000000,0.000000,25.000000,6.0,0,2,75.000000,0.000000,25.000000,5
3772,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,10,6,2026-03-10 18:01:08+00:00,True,300,https://www.chess.com/openings/Indian-Game-2.B...,fghsmn,3093,resigned,315f6280-8c1b-11e3-8036-000000000000,fabianocaruana,3260,-167,27889,167,0.948773,3176.5,False,loss,win,0.0,1.0,4,3.0,0,1,75.000000,0.0,25.000000,5,4.0,0,1,80.000000,0.000000,20.000000,7.0,0,2,77.777778,0.000000,22.222222,5
3921,Titled-Tuesday-Blitz-March-10-2026,2,300,2026-03-10 16:00:00+00:00,2026-03-10 18:13:56+00:00,1,11,2,2026-03-10 18:12:19+00:00,True,300,https://www.chess.com/openings/Nimzo-Indian-De...,fabianocaruana,3254,resigned,5ebdca54-8f15-11e2-800a-000000000000,magnuscarlsen,3365,-111,12321,111,0.967013,3309.5,False,loss,win,0.0,1.0,5,4.0,0,1,80.000000,0.0,20.000000,5,4.0,0,1,80.000000,0.000000,20.000000,8.0,0,2,80.000000,0.000000,20.000000,5

In [56]:
df.to_csv("titled_tuesday_games_finished_fromnotebook.csv", index=False)